(() => {
  const BO_API='https://wzawtpadchtnvtclyghm.supabase.co/functions/v1/bo-api';
  const API='https://wzawtpadchtnvtclyghm.supabase.co/functions/v1/receiving-nri-api';
  const $=id=>document.getElementById(id);
  let token=sessionStorage.getItem('rx_token')||'',conf=null,current=null,searchTimers=new WeakMap();

  async function bo(action,payload={}){const r=await fetch(BO_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({error:'Resposta inválida'}));if(!r.ok)throw new Error(d.error||'Erro de autenticação');return d}
  async function api(action,payload={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','x-bo-token':token},body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({error:'Resposta inválida'}));if(!r.ok)throw new Error(d.error||'Erro no recebimento');return d}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function show(id){['loginView','queueView','conferenceView','doneView','historyView'].forEach(x=>$(x).classList.toggle('hidden',x!==id));}
  function toast(m,e=false){const t=$('toast');t.textContent=m;t.classList.toggle('error',e);t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),2800)}
  function fmtDate(v){const p=String(v||'').slice(0,10).split('-');return p.length===3?p[2]+'/'+p[1]+'/'+p[0]:v||'—'}
  function status(s){return {awaiting_conference:'Aguardando',in_conference:'Em conferência',conference_completed:'Concluída'}[s]||s}

  async function loadConf(){try{const d=await bo('conferencers');$('confSelect').innerHTML='<option value="">Selecione...</option>'+d.conferencers.map(x=>'<option value="'+x.id+'">'+esc(x.display_name)+'</option>').join('')}catch(e){$('loginError').textContent=e.message}}
  $('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').textContent='';$('loginButton').disabled=true;try{const d=await bo('pin_login',{conferencer_id:$('confSelect').value,pin:$('pinInput').value});token=d.token;conf=d.conferencer;sessionStorage.setItem('rx_token',token);$('pinInput').value='';await openQueue()}catch(err){$('loginError').textContent=err.message}finally{$('loginButton').disabled=false}};
  $('logoutButton').onclick=()=>{token='';conf=null;sessionStorage.removeItem('rx_token');show('loginView')};
  $('backQueueButton').onclick=openQueue;$('doneBackButton').onclick=openQueue;$('historyBackButton').onclick=openQueue;$('historyButton').onclick=openHistory;

  function card(r,history=false){const action=!history&&(r.status==='awaiting_conference'||r.status==='in_conference')?'<button class="primary" data-start="'+r.id+'">'+(r.status==='in_conference'?'Continuar conferência':'Iniciar conferência')+'</button>':'';return '<article class="queue-card"><div class="queue-top"><div><div class="queue-name">'+esc(r.display_name)+'</div><p>'+esc(r.receipt_code)+' · Placa '+esc(r.plate||'—')+'</p></div><span class="badge '+r.status+'">'+status(r.status)+'</span></div><small>Chegada '+fmtDate(r.arrival_date)+' '+esc(String(r.arrival_time||'').slice(0,5))+' · NF '+esc(r.nf_imperio||r.nf_ambev||'—')+' · Pedido '+esc(r.order_number||'—')+'</small>'+action+'</article>'}
  async function openQueue(){show('queueView');$('loggedConf').textContent=conf?'Conferente: '+conf.display_name:'';$('queueList').innerHTML='<article class="queue-card">Carregando...</article>';try{const d=await api('conference_queue');$('queueList').innerHTML=d.receipts.length?d.receipts.map(r=>card(r)).join(''):'<article class="queue-card">Nenhuma carreta aguardando conferência.</article>';$('queueList').querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>start(Number(b.dataset.start)))}catch(e){if(e.message.includes('inválida')||e.message.includes('expirada')){token='';sessionStorage.removeItem('rx_token');show('loginView')}else $('queueList').innerHTML='<article class="queue-card error">'+esc(e.message)+'</article>'}}
  async function openHistory(){show('historyView');$('historyList').innerHTML='<article class="queue-card">Carregando...</article>';try{const d=await api('conference_history');$('historyList').innerHTML=d.receipts.length?d.receipts.map(r=>card(r,true)).join(''):'<article class="queue-card">Nenhuma conferência registrada.</article>'}catch(e){$('historyList').innerHTML='<article class="queue-card error">'+esc(e.message)+'</article>'}}

  async function start(id){try{const d=await api('conference_start',{id});current=d.receipt;openConference()}catch(e){toast(e.message,true);await openQueue()}}
  function openConference(){show('conferenceView');$('receiptTitle').textContent=current.display_name;$('receiptMeta').textContent=current.receipt_code+' · Placa '+(current.plate||'—')+' · Chegada '+fmtDate(current.arrival_date)+' '+String(current.arrival_time||'').slice(0,5);$('itemsList').innerHTML='';(current.items||[]).sort((a,b)=>a.line_no-b.line_no).forEach(x=>addItem(x));if(!$('itemsList').children.length)addItem();$('formError').textContent=''}

  function validity(card){const d=card.querySelector('.expiry').value;if(!d||!current)return;const days=Math.floor((Date.parse(d+'T12:00:00Z')-Date.parse(current.arrival_date+'T12:00:00Z'))/86400000),st=card.querySelector('.validity-status');st.textContent=days>=40?'OK':'NOK';st.className='validity-status '+(days>=40?'ok':'nok');card.querySelector('.validity-days').textContent=days+' dias entre recebimento e vencimento';}
  function setProduct(card,p){card.querySelector('.sku').value=p.sku_code;card.querySelector('.name').value=p.sku_name;card.dataset.name=p.sku_name;card.dataset.capacity=p.pallet_capacity??'';card.dataset.layer=p.layer_qty??'';card.dataset.curve=p.curve_class??'';card.querySelector('.capacity').textContent=p.pallet_capacity??'—';card.querySelector('.layer').textContent=p.layer_qty??'—';card.querySelector('.curve').textContent=p.curve_class||'—';card.querySelector('.capacity-input').value=p.pallet_capacity??'';card.querySelector('.layer-input').value=p.layer_qty??'';card.querySelector('.curve-input').value=p.curve_class??'';}
  function addItem(v={}){
    const card=$('itemTemplate').content.firstElementChild.cloneNode(true),list=$('itemsList');list.appendChild(card);renumber();
    card.querySelector('.remove').onclick=()=>{if(list.children.length===1)return toast('Inclua pelo menos um produto.',true);card.remove();renumber()};
    const sku=card.querySelector('.sku'),results=card.querySelector('.results');
    sku.addEventListener('input',()=>{card.querySelector('.name').value='';clearTimeout(searchTimers.get(sku));const q=sku.value.trim();if(!q){results.classList.add('hidden');return}searchTimers.set(sku,setTimeout(async()=>{try{const d=await api('catalog_search',{query:q});results.innerHTML=d.items.map(p=>'<button type="button" class="result" data-code="'+esc(p.sku_code)+'"><strong>'+esc(p.sku_code)+'</strong><small>'+esc(p.sku_name)+'</small></button>').join('')||'<div class="result">Código não encontrado.</div>';results._data=d.items;results.classList.remove('hidden')}catch(e){toast(e.message,true)}},220))});
    results.onclick=e=>{const b=e.target.closest('[data-code]');if(!b)return;const p=(results._data||[]).find(x=>x.sku_code===b.dataset.code);if(p)setProduct(card,p);results.classList.add('hidden')};
    card.querySelector('.expiry').onchange=()=>validity(card);
    if(v.sku_code){setProduct(card,{sku_code:v.sku_code,sku_name:v.sku_name,pallet_capacity:v.pallet_capacity,layer_qty:v.layer_qty,curve_class:v.curve_class});card.querySelector('.physical').value=v.physical_qty??'';card.querySelector('.pallets').value=v.pallet_count??'';card.querySelector('.unit').value=v.unit_text??'';card.querySelector('.expiry').value=String(v.expiry_date||'').slice(0,10);card.querySelector('.comment').value=v.comments??'';validity(card)}
  }
  function renumber(){[...$('itemsList').children].forEach((x,i)=>x.querySelector('.item-title').textContent='Produto '+(i+1))}
  $('addItemButton').onclick=()=>addItem();

  function collect(){return [...$('itemsList').children].map(card=>({sku_code:card.querySelector('.sku').value,physical_qty:card.querySelector('.physical').value,pallet_count:card.querySelector('.pallets').value,unit_text:card.querySelector('.unit').value,expiry_date:card.querySelector('.expiry').value,pallet_capacity:card.querySelector('.capacity-input').value,layer_qty:card.querySelector('.layer-input').value,curve_class:card.querySelector('.curve-input').value,comments:card.querySelector('.comment').value}))}
  $('saveDraftButton').onclick=async()=>{try{$('saveDraftButton').disabled=true;await api('conference_save',{id:current.id,items:collect()});toast('Rascunho salvo.')}catch(e){toast(e.message,true)}finally{$('saveDraftButton').disabled=false}};
  $('conferenceForm').onsubmit=async e=>{e.preventDefault();if(!confirm('Finalizar esta conferência?\n\nApós finalizar, o físico fica congelado para o cruzamento da Puxada e as NRIs são liberadas.'))return;$('formError').textContent='';$('finalizeButton').disabled=true;try{const d=await api('conference_finalize',{id:current.id,items:collect()});$('doneTitle').textContent=d.receipt.display_name;show('doneView')}catch(err){$('formError').textContent=err.message}finally{$('finalizeButton').disabled=false}};
  loadConf();show('loginView');
})();