export const palette=['#f47a20','#617e96','#32966f','#d6574d','#b5a088','#969ca6'];
export const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const format=(v,digits=1)=>v==null?'—':Number(v).toLocaleString('pt-BR',{maximumFractionDigits:digits});
const empty=message=>`<div class="efc-chart-empty">${escape(message||'Sem registros para este período.')}</div>`;
const access=(title,body)=>`<details class="efc-chart-data"><summary>Ver dados do gráfico</summary><div class="efc-table"><table><caption>${escape(title)}</caption>${body}</table></div></details>`;
export function seriesChart({id,title,data,series,percent=false,goal=null,bars=false,height=230}){
 if(!data.length||!data.some(d=>series.some(s=>d[s.key]!=null)))return empty();
 const width=700,left=52,right=20,top=25,bottom=47,plotW=width-left-right,plotH=height-top-bottom;
 const values=data.flatMap(d=>series.map(s=>d[s.key]).filter(v=>v!=null&&Number.isFinite(Number(v))).map(Number));const maximum=percent?Math.max(100,...values.map(v=>v>100?v*1.12:100)):Math.max(1,...values,goal??0)*1.13;
 const X=i=>left+plotW*(i+.5)/data.length,Y=v=>top+plotH*(1-v/maximum),baseline=top+plotH;
 const grid=Array.from({length:5},(_,i)=>{const v=maximum*i/4,y=Y(v);return `<line x1="${left}" x2="${width-right}" y1="${y}" y2="${y}" class="efc-gridline"/><text x="${left-10}" y="${y+4}" text-anchor="end" class="efc-axis">${format(v,0)}${percent?'%':''}</text>`;}).join('');
 const goalMark=goal!=null?`<line x1="${left}" x2="${width-right}" y1="${Y(goal)}" y2="${Y(goal)}" class="efc-goal-line"/><text x="${width-right}" y="${Math.max(14,Y(goal)-7)}" text-anchor="end" class="efc-goal-label">Meta ${format(goal)}${percent?'%':''}</text>`:'';
 const marks=series.map((s,si)=>{const color=s.color||palette[si%palette.length];if(bars){const bw=Math.min(36,plotW/data.length*.72)/series.length;return data.map((d,i)=>{if(d[s.key]==null)return '';const v=Number(d[s.key]),x=X(i)-bw*series.length/2+bw*si;return `<g class="efc-chart-point" data-chart-tip="${escape(d.tip||d.date||d.label)} · ${escape(s.label)}: ${format(v)}${percent?'%':''}" ${d.date?`data-efc-chart-day="${escape(d.date)}"`:''}><rect x="${x-2}" y="${top}" width="${bw+4}" height="${plotH}" fill="transparent"/><rect x="${x}" y="${Y(v)}" width="${Math.max(2,bw-2)}" height="${Math.max(0,baseline-Y(v))}" rx="3" fill="${color}"/>${data.length<=12?`<text x="${x+bw/2}" y="${Y(v)-7}" text-anchor="middle" class="efc-chart-value">${format(v,0)}</text>`:''}</g>`;}).join('');}
 const segments=[];let segment=[];for(let i=0;i<data.length;i++){const v=data[i][s.key];if(v==null){if(segment.length)segments.push(segment);segment=[];}else segment.push(`${X(i)},${Y(Number(v))}`);}if(segment.length)segments.push(segment);
 const line=segments.map(p=>`<polyline points="${p.join(' ')}" fill="none" stroke="${color}" stroke-width="2.8" stroke-linecap="round" stroke-linejoin="round"/>`).join('');const area=series.length===1?segments.filter(p=>p.length>1).map(p=>`<polygon points="${p[0].split(',')[0]},${baseline} ${p.join(' ')} ${p.at(-1).split(',')[0]},${baseline}" fill="${color}" opacity=".07"/>`).join(''):'';
 const points=data.map((d,i)=>d[s.key]==null?'':`<g class="efc-chart-point" data-chart-tip="${escape(d.tip||d.date||d.label)} · ${escape(s.label)}: ${format(d[s.key])}${percent?'%':''}" ${d.date?`data-efc-chart-day="${escape(d.date)}"`:''}><circle cx="${X(i)}" cy="${Y(d[s.key])}" r="13" fill="transparent"/><circle cx="${X(i)}" cy="${Y(d[s.key])}" r="3.6" fill="${color}" stroke="#fff" stroke-width="1.5"/></g>`).join('');return area+line+points;}).join('');
 const labels=data.map((d,i)=>`<text x="${X(i)}" y="${baseline+24}" text-anchor="middle" class="efc-axis efc-x-label" ${i%Math.ceil(data.length/8)!==0&&i!==data.length-1?'data-compact-hide="true"':''}>${escape(d.label)}</text>`).join('');
 const legend=series.map((s,i)=>`<span><i style="background:${s.color||palette[i%palette.length]}"></i>${escape(s.label)}</span>`).join('');
 return `<div class="efc-chart-wrap"><svg class="efc-chart-svg" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="${id}-title"><title id="${id}-title">${escape(title)}</title>${grid}${goalMark}${marks}${labels}<text x="${left}" y="14" class="efc-axis">${percent?'Percentual':escape(series.length===1?series[0].label:'Quantidade')}</text></svg><div class="efc-chart-legend">${legend}${goal!=null?'<span><i class="efc-dashed"></i>Meta</span>':''}</div></div>`+access(title,`<thead><tr><th>Período</th>${series.map(s=>`<th>${escape(s.label)}</th>`).join('')}</tr></thead><tbody>${data.map(d=>`<tr><td>${escape(d.date||d.label)}</td>${series.map(s=>`<td>${format(d[s.key])}${percent&&d[s.key]!=null?'%':''}</td>`).join('')}</tr>`).join('')}</tbody>`);
}
export function donutChart({id,title,data,center,subcenter=''}){const total=data.reduce((a,x)=>a+Math.max(0,x.value||0),0);if(!data.length)return empty('Sem volume conciliado para classificar.');const r=57,circumference=2*Math.PI*r;let offset=0;const rings=data.map((x,i)=>{const length=total?circumference*x.value/total:0,ring=`<circle cx="90" cy="90" r="${r}" fill="none" stroke="${palette[i%palette.length]}" stroke-width="19" stroke-dasharray="${length} ${circumference-length}" stroke-dashoffset="${-offset}" transform="rotate(-90 90 90)" class="efc-chart-point" data-chart-tip="${escape(x.label)}: ${format(x.value,0)} (${format(total?100*x.value/total:0)}%)"/>`;offset+=length;return ring;}).join('');return `<div class="efc-donut-layout"><svg class="efc-donut-svg" viewBox="0 0 180 180" role="img" aria-labelledby="${id}-title"><title id="${id}-title">${escape(title)}</title><circle cx="90" cy="90" r="${r}" fill="none" stroke="#eeeae0" stroke-width="19"/>${rings}<text x="90" y="88" text-anchor="middle" class="efc-donut-total">${escape(center??format(total,0))}</text><text x="90" y="108" text-anchor="middle" class="efc-donut-sub">${escape(subcenter)}</text></svg><div class="efc-donut-legend">${data.map((x,i)=>`<div><i style="background:${palette[i%palette.length]}"></i><span>${escape(x.label)}</span><b>${format(x.value,0)}</b><small>${format(total?100*x.value/total:0)}%</small></div>`).join('')}</div></div>`;}
export function horizontalBars({title,data,limit=10,unit='',percent=false,color=null}){const selected=data.slice(0,limit),maximum=percent?Math.max(100,...selected.map(x=>x.value||0)):Math.max(1,...selected.map(x=>x.value||0));if(!selected.length)return empty();return `<div class="efc-horizontal-bars" role="img" aria-label="${escape(title)}">${selected.map((x,i)=>`<div class="efc-bar-row" ${x.name?`data-efc-chart-member="${escape(x.name)}"`:''}><div class="efc-bar-caption"><span title="${escape(x.label)}">${escape(x.label)}</span><b>${format(x.value)}${percent?'%':unit?' '+escape(unit):''}</b></div><div class="efc-bar-track"><i style="width:${Math.min(100,Math.max(0,100*x.value/maximum))}%;background:${color||palette[i%palette.length]}"></i></div>${x.detail?`<small>${escape(x.detail)}</small>`:''}</div>`).join('')}</div>`;}
export function chartPanel(title,subtitle,body,extra='',wide=false){return `<section class="efc-visual-panel ${wide?'efc-wide-panel':''}"><header class="efc-chart-heading"><div><h2>${escape(title)}</h2>${subtitle?`<p>${escape(subtitle)}</p>`:''}</div>${extra}</header>${body}</section>`;}
export function metric(label,value,detail='',rate=null,goal=null,tone=''){const has=rate!=null;return `<article class="efc-vmetric ${tone}"><span>${escape(label)}</span><strong>${escape(value)}</strong>${has?`<div class="efc-metric-track"><i style="width:${Math.min(100,Math.max(0,rate*100))}%;background:${goal!=null&&rate<goal?'#d6574d':'#32966f'}"></i>${goal!=null?`<b style="left:${goal*100}%" title="Meta ${format(goal*100)}%"></b>`:''}</div>`:''}<small>${escape(detail)}</small></article>`;}
