import {escape as e,format as n} from './efc-charts.mjs?v=20261006-pay-model';
const numeric=v=>typeof v==='number'&&Number.isFinite(v);
const value=(v,digits=2)=>numeric(v)?n(v,digits):'—';
const percent=v=>numeric(v)?n(v*100,2)+'%':'—';
function matrix(title,headers,rows){return `<section class="efc-panel efc-pay-panel"><h2>${e(title)}</h2><div class="efc-pay-table"><table><thead><tr>${headers.map(h=>`<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((v,i)=>`<td data-label="${e(headers[i])}">${e(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`;}
export function remunerationModel(c){
 if(c.history)return '';
 const source=c.legacy_pay||[];
 if(!source.some(x=>numeric(x.model_base)))return '<section class="efc-panel"><h2>Modelo de remuneração</h2><p>A tabela de pagamentos da planilha não está disponível neste mês.</p></section>';
 const total=source.reduce((a,x)=>a+(numeric(x.cached_payment)?x.cached_payment:0),0);
 const payRows=source.map(x=>[x.name,value(x.cached_pallets),value(x.model_base),value(x.model_error_bonus),value(x.model_damage_bonus),value(x.model_efficiency_bonus),value(x.model_absence_bonus),value(x.cached_payment)]);
 payRows.push(['TOTAL',value(source.reduce((a,x)=>a+(x.cached_pallets||0),0)),...['model_base','model_error_bonus','model_damage_bonus','model_efficiency_bonus','model_absence_bonus','cached_payment'].map(k=>value(source.reduce((a,x)=>a+(numeric(x[k])?x[k]:0),0)))]);
 return `<div class="efc-pay-model"><div class="efc-pay-heading"><div><h2>Modelo de remuneração dos ajudantes</h2><p>Valores salvos na planilha do mês. O fechamento atualizado depende da validação das bases e da presença.</p></div><div class="efc-pay-total"><span>Total na planilha</span><strong>R$ ${n(total,2)}</strong></div></div>${matrix('Pagamentos da planilha',['Colaborador','Pallets','Produtividade R$','Erros R$','Avarias R$','Eficiência R$','Faltas R$','Final R$'],payRows)}<details class="efc-panel efc-pay-rules"><summary>Critérios de remuneração</summary><div class="efc-pay-rule-grid"><p><b>Produtividade</b>Valor por pallet conforme a classificação pela média diária: 1º ao 5º R$ 0,92; 6º ao 9º R$ 0,84; a partir do 10º R$ 0,77.</p><p><b>Erros</b>Até 0,5% das caixas: +10% da produtividade. Acima: −10%.</p><p><b>Avarias</b>Abaixo de R$ 40: +10% da produtividade. A partir de R$ 40: −10%.</p><p><b>Eficiência</b>EFC da equipe a partir de 96%: +10% da produtividade.</p><p><b>Faltas</b>Sem faltas: +10% da produtividade. Uma falta: −15%; duas: −30%; três ou mais: −50% do subtotal após erros, avarias e eficiência.</p><p><b>Média diária</b>Pallets ÷ (dias do período − faltas − compensações). Final: produtividade + todos os bônus e descontos.</p></div></details><details class="efc-panel efc-pay-info"><summary>Informações do modelo da planilha</summary>${matrix('Produção e qualidade',['Colaborador','Caixas','Min/pallet','Pallets/h','Erros','Taxa erros','Avarias R$','EFM'],source.map(x=>[x.name,value(x.cached_boxes,0),value(numeric(x.model_average_time)?x.model_average_time*1440:null),value(x.model_pallets_hour),value(x.model_errors,0),percent(x.model_error_rate),value(x.model_damages),percent(x.model_efm)]))}${matrix('Classificação e presença',['Colaborador','Classificação','Pallets/dia','Faltas','Compensações'],source.map(x=>[x.name,value(x.model_rank,0),value(x.model_average_pallets),x.absences==null?'Pendente':value(x.absences,0),x.compensation==null?'Pendente':value(x.compensation,0)]))}</details></div>`;
}
