(() => {
  const API='https://wzawtpadchtnvtclyghm.supabase.co/functions/v1/stock-api';
  const S={data:null,date:'',query:'',status:''};
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const nf=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2});
  const dt=v=>v?String(v).slice(0,10).split('-').reverse().join('/'):'—';
  async function call(action,payload={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','x-session-token':window.state?.token||''},body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({error:'Resposta inválida'}));if(!r.ok)throw new Error(d.error||'Falha no OOR');return d;}
  function view(){let v=$('stockOorView');if(v)return v;const main=document.querySelector('main');if(!main)return null;v=document.createElement('section');v.id='stockOorView';v.className='view hidden';main.appendChild(v);return v;}
  async function load(){const root=view();if(!root)return;root.innerHTML='<div class="oor-loading">Carregando OOR…</div>';try{S.data=await call('oor_get',S.date?{reference_date:S.date}:{});S.date=S.data.reference_date||'';render();}catch(e){root.innerHTML='<div class="oor-empty"><strong>Não foi possível carregar o OOR</strong><span>'+esc(e.message)+'</span></div>';}}
  function filtered(){const q=S.query.trim().toLowerCase();return (S.data?.rows||[]).filter(x=>(!S.status||x.status===S.status)&&(!q||String(x.sku_code).includes(q)||String(x.sku_name||'').toLowerCase().includes(q)));}
  function render(){const root=view();if(!root)return;const d=S.data||{},rows=filtered(),c=d.counts||{};
    root.innerHTML='<div class="oor">'+
      '<section class="oor-top"><div><strong>'+dt(d.reference_date)+'</strong><small>Política '+esc(d.policy?.code||'—')+' · '+esc(d.policy?.status==='approved'?'Vigente':'—')+'</small></div><label>Data<select id="oorDate">'+(d.dates||[]).map(x=>'<option value="'+esc(x)+'" '+(x===d.reference_date?'selected':'')+'>'+dt(x)+'</option>').join('')+'</select></label></section>'+
      '<section class="oor-kpis"><button data-status="OUT"><small>OUT</small><strong>'+Number(c.OUT||0)+'</strong></button><button data-status="OVER"><small>OVER</small><strong>'+Number(c.OVER||0)+'</strong></button><button data-status="OK"><small>OK</small><strong>'+Number(c.OK||0)+'</strong></button></section>'+
      '<section class="oor-tools"><div><input id="oorSearch" placeholder="Buscar SKU ou produto" value="'+esc(S.query)+'"><select id="oorStatus"><option value="">Todos os status</option><option value="OUT" '+(S.status==='OUT'?'selected':'')+'>OUT</option><option value="OVER" '+(S.status==='OVER'?'selected':'')+'>OVER</option><option value="OK" '+(S.status==='OK'?'selected':'')+'>OK</option></select></div><span>'+rows.length+' SKUs</span></section>'+
      '<section class="oor-table"><table><thead><tr><th>SKU</th><th>Produto</th><th>Unidade</th><th>Disponível</th><th>Mínimo da política</th><th>Máximo da política</th><th>Status</th></tr></thead><tbody>'+
      (rows.length?rows.map(x=>'<tr><td><strong>'+esc(x.sku_code)+'</strong></td><td>'+esc(x.sku_name||'')+'</td><td>'+esc(x.unit_code||'—')+'</td><td class="qty">'+nf.format(Number(x.available_qty||0))+'</td><td>'+nf.format(Number(x.out_qty||0))+'</td><td>'+nf.format(Number(x.over_qty||0))+'</td><td><span class="oor-status '+String(x.status||'').toLowerCase()+'">'+esc(x.status||'—')+'</span></td></tr>').join(''):'<tr><td colspan="7" class="empty-row">Nenhum SKU encontrado.</td></tr>')+
      '</tbody></table></section><p class="oor-foot">OOR é diário: disponível ≤ Mínimo = OUT; disponível ≥ Máximo = OVER; entre os limites = OK.</p></div>';
    $('oorDate').onchange=async e=>{S.date=e.target.value;await load();};$('oorSearch').oninput=e=>{S.query=e.target.value;render();};$('oorStatus').onchange=e=>{S.status=e.target.value;render();};root.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{S.status=S.status===b.dataset.status?'':b.dataset.status;render();});
  }
  async function open(){const v=view();if(!v)return;document.querySelectorAll('main > .view').forEach(x=>x.classList.add('hidden'));document.querySelectorAll('.nav-link').forEach(x=>x.classList.remove('active'));v.classList.remove('hidden');document.querySelector('[data-view="pull-oor"]')?.classList.add('active');document.querySelector('.pull-nav-group')?.classList.add('open');$('sidebar')?.classList.remove('open');if($('pageTitle'))$('pageTitle').textContent='OOR';if($('pageSubtitle'))$('pageSubtitle').textContent='Leitura diária contra o Mínimo e o Máximo da política vigente.';await load();}
  function install(){view();if(!$('stockOorCss')){const l=document.createElement('link');l.id='stockOorCss';l.rel='stylesheet';l.href='oor.css?v=20260923-2';document.head.appendChild(l);}window.__stockOor={open,reload:load};}
  install();
})();