(() => {
 const API='https://wzawtpadchtnvtclyghm.supabase.co/functions/v1/stock-api';
 const S={data:null,month:state.currentMonth,area:'Regulador',query:'',mode:'map',active:'',request:0};
 let core;
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const nf=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2});
 const dt=x=>x?x.slice(0,10).split('-').reverse().join('/'):'Não informada';
 const norm=x=>String(x||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const areaName=a=>a==='Regulador'?'Estoque geral':a;
 const badge=c=>`<span class="stock-badge ${['A','B','C'].includes(c)?c.toLowerCase():'unknown'}">${esc(c||'Sem curva')}</span>`;
 const table=(heads,rows)=>`<div class="stock-table-wrap"><table><thead><tr>${heads.map(h=>'<th>'+h+'</th>').join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
 async function call(action,payload={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','x-session-token':state.token},body:JSON.stringify({action,...payload})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao consultar estoque');return d;}
 async function load(force=false){if(!force&&S.data?.month===S.month)return S.data;const request=++S.request,month=S.month;const data=await call('get',{month});if(request!==S.request)return null;S.data={...data,month};return S.data;}
 const meta=()=>S.data?.snapshot?`Base de ${dt(S.data.snapshot.as_of)} · Curva ABC ${S.month.split('-').reverse().join('/')} · Dados da última atualização do estoque`:'Nenhuma base importada';
 const matches=r=>!S.query||norm([r.address,r.sku_code,r.sku_name].join(' ')).includes(norm(S.query));
 const actions=()=>`<button class="outline-button" data-refresh>Atualizar consulta</button>${state.user?.role==='admin'?'<button class="primary-button" data-import>Importar estoque</button>':''}`;
 function bindActions(root){root.querySelector('[data-refresh]')?.addEventListener('click',refresh);root.querySelector('[data-import]')?.addEventListener('click',openImport);}
 async function refresh(){try{await load(true);renderActive();showToast('Consulta atualizada.');}catch(e){showToast(e.message,true);}}
 function hideViews(){document.querySelectorAll('main > .view').forEach(x=>x.classList.add('hidden'));document.querySelectorAll('.nav-link').forEach(x=>x.classList.remove('active'));$('sidebar')?.classList.remove('open');}
 function openArea(area){S.active='layout';S.area=area;hideViews();$('layoutView').classList.remove('hidden');document.querySelector('[data-view="layout"]')?.classList.add('active');$('pageTitle').textContent='Layout';$('pageSubtitle').textContent='Áreas físicas e estoque por endereço.';document.querySelectorAll('[data-layout-panel]').forEach(x=>x.classList.add('hidden'));document.querySelectorAll('[data-layout-tab]').forEach(x=>x.classList.toggle('active',x.dataset.stockArea===area));$('stockLayoutPanel').classList.remove('hidden');$('stockLayoutPanel').innerHTML='<p class="stock-empty">Carregando estoque…</p>';load().then(renderLayout).catch(e=>$('stockLayoutPanel').innerHTML=`<p class="stock-error">${esc(e.message)}</p>`);}
 function openFefo(code='',area='Regulador'){S.active='fefo';hideViews();$('replenishmentView').classList.remove('hidden');document.querySelector('[data-view="replenishment"]').classList.add('active');$('pageTitle').textContent='Reabastecimento';$('pageSubtitle').textContent='Localização e ordem de consumo por validade.';S.code=code;S.origin=area;$('replenishmentView').innerHTML='<p class="stock-empty">Carregando estoque…</p>';load().then(renderFefo).catch(e=>$('replenishmentView').innerHTML=`<p class="stock-error">${esc(e.message)}</p>`);}
 function renderActive(){if(S.active==='layout')renderLayout();if(S.active==='fefo')renderFefo();if(!$('abcView').classList.contains('hidden'))renderAdherence();}
 function renderLayout(){
  if(S.active!=='layout')return;
  const root=$('stockLayoutPanel'),d=S.data;if(!d?.snapshot){root.innerHTML='<p class="stock-empty">Nenhuma base importada.</p>';return;}
  const locs=d.locations.filter(l=>l.area===S.area),rows=d.rows.filter(r=>r.area===S.area&&r.sku_code),known=rows.reduce((s,r)=>s+(r.pallets||0),0);
  root.innerHTML=`<div class="stock-module"><div class="stock-heading"><div><p class="eyebrow">ÁREA FÍSICA</p><h2>${esc(areaName(S.area))}</h2><p>${esc(meta())}</p></div><div class="stock-actions">${actions()}</div></div><div class="stock-toolbar"><label>Curva ABC de referência<select id="stockMonth">${MONTHS.map(([k,l])=>`<option value="${k}" ${k===S.month?'selected':''}>${l}/2026</option>`).join('')}</select></label><label class="stock-search">Localizar produto ou endereço<input id="stockSearch" value="${esc(S.query)}" placeholder="Código, descrição ou rua"/></label><div class="stock-view-toggle"><button id="stockMapToggle" class="${S.mode==='map'?'active':''}">Mapa</button><button id="stockListToggle" class="${S.mode==='list'?'active':''}">Base de ruas</button></div></div><div class="stock-kpis"><article><small>Endereços ocupados</small><strong>${locs.filter(l=>l.occupied).length}<em> / ${locs.length}</em></strong></article><article><small>SKUs presentes</small><strong>${new Set(rows.map(r=>r.sku_code)).size}</strong></article><article><small>Paletes informados</small><strong>${nf.format(known)}</strong><span>${rows.filter(r=>r.pallets==null).length} registros sem quantidade</span></article><article><small>Produtos sem validade</small><strong>${rows.filter(r=>!r.expires_on).length}</strong></article></div><div class="stock-legend">${badge('A')} ${badge('B')} ${badge('C')} ${badge('Mista')} <span>Vazio / sem curva em cinza</span></div>${S.area==='Câmara Fria'?'<p class="stock-notice">As 14 posições vieram da aba Chopp. Validade e quantidade não foram informadas; complete a base para utilizar FEFO.</p>':''}<div id="stockMapContent"></div><div id="stockLocationDetails"></div></div>`;
  bindActions(root);$('stockMonth').onchange=async e=>{S.month=e.target.value;try{await load();renderLayout();}catch(e){showToast(e.message,true);}};$('stockSearch').oninput=e=>{S.query=e.target.value;renderMapContent();};$('stockMapToggle').onclick=()=>{S.mode='map';renderLayout();};$('stockListToggle').onclick=()=>{S.mode='list';renderLayout();};renderMapContent();
 }
 function locationButton(loc,label,style=''){const codes=[...new Set((loc?.rows||[]).filter(r=>r.sku_code).map(r=>r.sku_code))];return `<button class="stock-cell ${loc?.occupied?'occupied':''} ${['A','B','C'].includes(loc?.curve)?loc.curve.toLowerCase():'unknown'} ${S.query&&(!loc||!loc.rows.some(matches))?'muted':''}" style="${style}" data-location="${esc(loc?.key||'')}" title="${esc(label+' · '+codes.join(', '))}"><strong>${esc(label)}</strong><span>${codes.length>1?codes.length+' SKUs':codes[0]||(loc?'Vazio':'Sem base')}</span></button>`;}
 function renderMapContent(){
  const root=$('stockMapContent'),d=S.data,locs=d.locations.filter(l=>l.area===S.area),byKey=new Map(locs.map(l=>[l.key,l]));
  if(S.mode==='list'){
   const rows=d.rows.filter(r=>r.area===S.area&&matches(r));
   root.innerHTML=`<p class="stock-help">Cada linha preserva o registro de origem. Uma rua pode conter mais de um lote.</p>${table(['Endereço','Código / produto','Curva','Recebimento','Validade','Paletes','Situação',''],rows.map(r=>`<tr><td><button class="stock-link" data-location="${esc(core.keyOf(r))}">${esc(r.address)}</button></td><td><strong>${esc(r.sku_code||'Vazio')}</strong><small>${esc(r.sku_name)}</small></td><td>${badge(r.curve)}</td><td>${dt(r.received_on)}</td><td>${dt(r.expires_on)}</td><td>${r.pallets==null?'Não informados':nf.format(r.pallets)}</td><td>${esc(r.fefo_status)}</td><td>${state.user?.role==='admin'?`<button class="stock-link" data-edit="${esc(r.id)}">Editar</button>`:''}</td></tr>`))}`;
  }else{
   const anchors=d.snapshot.payload.maps[S.area]?.anchors||[],mapped=new Set(anchors.map(a=>S.area+':'+core.normalizeAddress(a.address)));
  const minC=Math.min(...anchors.map(a=>a.col)),minR=Math.min(...anchors.map(a=>a.row)),maxC=Math.max(...anchors.map(a=>a.col+(a.width||1)-1)),maxR=Math.max(...anchors.map(a=>a.row+(a.height||1)-1)),unit=S.area==='Regulador'?46:68,rh=S.area==='Regulador'?42:52;
   root.innerHTML=`<p class="stock-help">Posições relativas da aba ${esc(d.snapshot.payload.maps[S.area]?.sheet)}. Clique no endereço para ver todos os lotes. Use a rolagem para percorrer o mapa.</p><div class="stock-map-scroll" tabindex="0" aria-label="Mapa de ${esc(areaName(S.area))}"><div class="stock-map" style="width:${(maxC-minC+2)*unit}px;height:${(maxR-minR+2)*rh}px">${anchors.map(a=>locationButton(byKey.get(S.area+':'+core.normalizeAddress(a.address)),a.address,`left:${(a.col-minC)*unit}px;top:${(a.row-minR)*rh}px;width:${unit*(a.width||1)-3}px;height:${rh*(a.height||1)-4}px`)).join('')}</div></div>`;
   const extras=locs.filter(l=>!mapped.has(l.key));if(extras.length)root.innerHTML+=`<details class="stock-unmapped"><summary>${extras.length} endereços da base sem posição desenhada na planilha</summary><div class="stock-extra-grid">${extras.map(l=>locationButton(l,l.address)).join('')}</div></details>`;
  }
  if(S.mode==='map'){
   const controls=document.createElement('div');controls.className='stock-map-controls';controls.innerHTML='<label>Ampliação <select aria-label="Ampliação do mapa"><option value="0.25">25% · Visão geral</option><option value="0.5">50%</option><option value="0.75">75%</option><option value="1">100% · Detalhes</option><option value="1.5">150%</option></select></label>';
   const zoom=S.zoom?.[S.area]||(S.area==='Regulador'?0.25:S.area==='Marketplace'?0.75:1),map=root.querySelector('.stock-map');controls.querySelector('select').value=String(zoom);map.style.zoom=zoom;
   controls.querySelector('select').onchange=e=>{S.zoom||={};S.zoom[S.area]=Number(e.target.value);map.style.zoom=e.target.value;};root.querySelector('.stock-map-scroll').before(controls);
  }
  root.querySelectorAll('[data-location]').forEach(b=>b.onclick=()=>showLocation(b.dataset.location));root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editRow(b.dataset.edit));
 }
 function showLocation(key){
  const loc=S.data.locations.find(l=>l.key===key);if(!loc){showToast('Endereço sem registro na Base Ruas.',true);return;}const root=$('stockLocationDetails');
  root.innerHTML=`<article class="panel stock-details"><div class="stock-heading"><h3>${esc(areaName(loc.area))} · ${esc(loc.address)}</h3><button class="outline-button" id="stockDetailClose">Fechar</button></div>${table(['Produto','Validade','Paletes','FEFO',''],loc.rows.map(r=>`<tr><td><strong>${esc(r.sku_code||'Vazio')}</strong><small>${esc(r.sku_name)}</small></td><td>${dt(r.expires_on)}</td><td>${r.pallets==null?'Não informados':nf.format(r.pallets)}</td><td>${esc(r.fefo_status)}</td><td>${r.sku_code?`<button class="stock-link" data-fefo="${esc(r.sku_code)}">Consultar FEFO</button>`:''} ${state.user?.role==='admin'?`<button class="stock-link" data-edit="${esc(r.id)}">Editar</button>`:''}</td></tr>`))}</article>`;
  $('stockDetailClose').onclick=()=>root.innerHTML='';root.querySelectorAll('[data-fefo]').forEach(b=>b.onclick=()=>openFefo(b.dataset.fefo,loc.area));root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editRow(b.dataset.edit));root.scrollIntoView({behavior:'smooth',block:'nearest'});
 }
 function renderFefo(){
  if(S.active!=='fefo')return;const root=$('replenishmentView');if(!S.data?.snapshot){root.innerHTML='<p class="stock-empty">Nenhuma base importada.</p>';return;}
  const products=[...new Map(S.data.rows.filter(r=>r.sku_code).map(r=>[r.sku_code,r])).values()];
  root.innerHTML=`<div class="stock-module"><div class="stock-heading"><div><p class="eyebrow">ESTOQUE → PICKING</p><h2>Qual lote consumir primeiro?</h2><p>${esc(meta())}</p></div><div class="stock-actions">${actions()}</div></div><div class="stock-toolbar"><label class="stock-search">Código do produto<input id="fefoSku" list="stockProducts" value="${esc(S.code||'')}" placeholder="Digite ou selecione o SKU"/><datalist id="stockProducts">${products.map(r=>`<option value="${esc(r.sku_code)}">${esc(r.sku_name)}</option>`).join('')}</datalist></label><label>Área de origem<select id="fefoArea">${core.AREAS.map(a=>`<option ${a===S.origin?'selected':''}>${esc(a)}</option>`).join('')}</select></label><button class="primary-button" id="fefoConsult">Consultar FEFO</button></div><div id="fefoResult"></div><details class="stock-method"><summary>Critérios de consumo</summary><p>Primeiro vence, primeiro sai. A ordem é calculada pela validade, com recebimento e endereço como desempate. Endereços com a mesma validade têm a mesma prioridade. Lotes vencidos, que vencem hoje, sem validade, com trava-palete ou com recebimento inconsistente não são recomendados.</p><p>Devolução: menos de 40 dias entre recebimento e validade, conforme a planilha. Sem recebimento, essa verificação fica pendente. Quantidade não informada exige conferência física. A consulta não dá baixa automática no estoque.</p></details></div>`;
  bindActions(root);$('fefoConsult').onclick=()=>{S.code=$('fefoSku').value.trim();S.origin=$('fefoArea').value;renderFefoResult();};$('fefoSku').onkeydown=e=>{if(e.key==='Enter')$('fefoConsult').click();};$('fefoArea').onchange=()=>{S.origin=$('fefoArea').value;renderFefoResult();};renderFefoResult();
 }
 function renderFefoResult(){
  const root=$('fefoResult');if(!S.code){root.innerHTML='<div class="stock-empty">Selecione um produto para consultar as ruas e a sequência de consumo.</div>';return;}
  const rows=core.fefoRows(S.data.rows,S.code,S.origin),ready=rows.filter(r=>['Prioridade FEFO','Aguardar lote anterior'].includes(r.fefo_status)),first=ready[0],dates=[...new Set(ready.map(r=>r.expires_on))];
  root.innerHTML=`<div class="stock-recommend ${first?'':'blocked'}"><small>${first?'CONSUMIR PRIMEIRO':'NENHUM LOTE RECOMENDADO'}</small><h3>${first?esc([...new Set(ready.filter(r=>r.expires_on===first.expires_on).map(r=>r.address))].join(' · ')):'Verifique as pendências abaixo'}</h3><p>${first?`Validade ${dt(first.expires_on)} · ${first.days} dias restantes`:'Não há lote com validade e condição de consumo válidas nesta área.'}</p><span>${esc(rows[0]?.sku_name||'Produto não encontrado na base')}</span></div>${table(['Prioridade','Endereço','Recebimento','Validade','Dias','Paletes','Condição',''],rows.map(r=>`<tr><td>${['Prioridade FEFO','Aguardar lote anterior'].includes(r.fefo_status)?dates.indexOf(r.expires_on)+1:'—'}</td><td><strong>${esc(r.address)}</strong><small>${esc(areaName(r.area))}</small></td><td>${dt(r.received_on)}</td><td>${dt(r.expires_on)}</td><td>${r.days??'—'}</td><td>${r.pallets==null?'Conferir saldo':nf.format(r.pallets)}</td><td><span class="stock-status ${r.fefo_status==='Prioridade FEFO'?'ready':''}">${esc(r.fefo_status)}</span>${!r.received_on?'<small>Recebimento não informado</small>':''}</td><td><button class="stock-link" data-map="${esc(r.address)}">Ver no layout</button></td></tr>`))}`;
  root.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>{S.query=b.dataset.map;openArea(S.origin);});
 }
 async function openAdherence(){S.month=state.currentMonth;const root=$('stockAdherenceBody');root.innerHTML='<p class="stock-empty">Cruzando estoque com Curva ABC…</p>';try{await load();renderAdherence();}catch(e){root.innerHTML=`<p class="stock-error">${esc(e.message)}</p>`;}}
 function renderAdherence(){
  const root=$('stockAdherenceBody');if(!root||!S.data?.snapshot)return;
  root.innerHTML=`<p class="stock-help">${esc(meta())}. Estoque atual comparado à curva do mês selecionado; não representa um inventário histórico daquele mês.</p><div class="stock-adherence-cards">${S.data.adherence.map(a=>`<article><small>${esc(areaName(a.area))}</small><strong>${a.rate===null?'—':nf.format(a.rate*100)+'%'}</strong><p>${a.real} posições A / meta ${a.planned}</p><span>${a.monitored} endereços monitorados · ${a.checks.filter(c=>c.status==='Sem curva').length} sem curva</span></article>`).join('')}</div><p class="stock-help">Aderência = posições monitoradas ocupadas exclusivamente por curva A ÷ meta. Endereços vazios, mistos ou sem curva não contam como aderentes. Picking mantém seu croqui calculado; o 100% fixo da planilha não é usado como medição.</p>${S.data.adherence.map(a=>`<details class="stock-method"><summary>${esc(areaName(a.area))}: ${a.checks.filter(c=>c.status!=='Aderente').length} endereços a revisar</summary>${table(['Endereço','Curva presente','Esperada','Situação'],a.checks.map(c=>`<tr><td>${esc(c.address)}</td><td>${badge(c.curve)}</td><td>${badge('A')}</td><td>${esc(c.status)}</td></tr>`))}</details>`).join('')}<details class="stock-method"><summary>Origem e critérios das metas</summary>${(S.data.snapshot.payload.notes||[]).map(n=>`<p>${esc(n)}</p>`).join('')}</details>`;
 }
 function dialog(title,body){$('stockDialog')?.remove();const d=document.createElement('dialog');d.id='stockDialog';d.className='stock-dialog';d.innerHTML=`<div class="stock-heading"><h2>${esc(title)}</h2><button class="outline-button" id="stockDialogClose">Fechar</button></div>${body}<p class="stock-error" id="stockDialogError"></p>`;document.body.appendChild(d);$('stockDialogClose').onclick=()=>d.close();d.showModal();return d;}
 async function save(payload){await call('save',{previous_id:S.data.snapshot.id,payload});S.data=null;await load(true);renderActive();}
 function editRow(id){
  const row=S.data.rows.find(r=>r.id===id);if(!row||state.user?.role!=='admin')return;
  const d=dialog('Atualizar registro do estoque',`<p>${esc(areaName(row.area))} · ${esc(row.address)} · origem ${esc(row.source_sheet)} ${row.source_row}</p><form id="stockEditForm" class="stock-form"><label>Código<input name="sku_code" value="${esc(row.sku_code||'')}" pattern="[0-9]*"/></label><label>Produto<input name="sku_name" value="${esc(row.sku_name)}"/></label><label>Recebimento<input name="received_on" type="date" value="${esc(row.received_on||'')}"/></label><label>Validade<input name="expires_on" type="date" value="${esc(row.expires_on||'')}"/></label><label>Quantidade (paletes)<input name="pallets" type="number" min="0" step="any" value="${row.pallets??''}"/></label><label>Trava-palete / motivo<input name="lock" value="${esc(row.lock)}" placeholder="Vazio = sem trava manual"/></label><button class="primary-button" type="submit">Salvar atualização</button></form>`);
  $('stockEditForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const f=Object.fromEntries(new FormData(e.target)),p=structuredClone(S.data.snapshot.payload),r=p.rows.find(x=>x.id===id);Object.assign(r,{sku_code:f.sku_code||null,sku_name:f.sku_name,received_on:f.received_on||null,expires_on:f.expires_on||null,pallets:f.pallets===''?null:Number(f.pallets),lock:f.lock,inventory_confirmed:true});p.source_name='Atualização no painel';await save(p);d.close();showToast('Estoque atualizado nos módulos.');}catch(e){$('stockDialogError').textContent=e.message;}finally{b.disabled=false;}};
 }
 async function openImport(){
  if(state.user?.role!=='admin')return;
  const d=dialog('Importar Estoque x Estoque',`<p>A nova base atualiza os três layouts, o FEFO e a aderência. A versão anterior fica preservada.</p><div class="stock-form"><label>Planilha<input id="stockFile" type="file" accept=".xlsx"/></label><label>Data de referência<input id="stockAsOf" type="date" value="${esc(S.data?.snapshot?.as_of||new Date().toISOString().slice(0,10))}"/></label></div><div id="stockImportPreview"></div><button class="primary-button" id="stockImportConfirm" disabled>Publicar base</button>`);let pending;
  $('stockFile').onchange=async e=>{pending=null;$('stockImportConfirm').disabled=true;const file=e.target.files[0];if(!file)return;try{$('stockImportPreview').textContent='Lendo Base Ruas…';if(!window.XLSX)await readRows(file);const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});pending=parseWorkbook(wb,file.name);$('stockAsOf').value=pending.as_of;$('stockImportPreview').innerHTML=`<p>${pending.rows.length} registros · ${pending.rows.filter(r=>r.sku_code).length} com produto · ${pending.rows.filter(r=>r.sku_code&&!r.expires_on).length} sem validade.</p><p>Revise a data de referência antes de publicar.</p>`;$('stockImportConfirm').disabled=false;}catch(e){$('stockImportPreview').textContent='';$('stockDialogError').textContent=e.message;}};
  $('stockImportConfirm').onclick=async()=>{const b=$('stockImportConfirm');b.disabled=true;try{pending.as_of=$('stockAsOf').value;core.validateSnapshot(pending);await save(pending);d.close();showToast('Base integrada atualizada.');}catch(e){$('stockDialogError').textContent=e.message;}finally{b.disabled=false;}};
 }
 function parseWorkbook(wb,name){
  const sheetName=wb.SheetNames.find(n=>norm(n)==='base ruas');if(!sheetName)throw new Error('Aba Base Ruas não encontrada.');
  const data=XLSX.utils.sheet_to_json(wb.Sheets[sheetName],{header:1,raw:true,defval:null});const head=data.findIndex(r=>r.some(x=>norm(x)==='rua')&&r.some(x=>norm(x)==='validade'));if(head<0)throw new Error('Cabeçalhos da Base Ruas não encontrados.');
  const headers=data[head].map(norm),col=n=>headers.indexOf(n),loc=col('rua'),sku=col('codigo'),prod=col('produto'),rec=col('recebimento'),exp=col('validade'),qty=col('quantidade (plt)'),lock=col('trava-palete');if([loc,sku,rec,exp,qty].some(i=>i<0))throw new Error('Colunas de rua, código, recebimento, validade ou quantidade ausentes.');
  const iso=(x,line)=>{if(x==null||x==='')return null;if(x instanceof Date)return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`;if(typeof x==='number'){const z=XLSX.SSF.parse_date_code(x);return z?`${z.y}-${String(z.m).padStart(2,'0')}-${String(z.d).padStart(2,'0')}`:null;}const m=String(x).match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;if(/^\d{4}-\d{2}-\d{2}$/.test(String(x)))return x;throw new Error('Data inválida na linha '+line);};
  let marketplace=false;const rows=[];for(let i=head+1;i<data.length;i++){const r=data[i],address=String(r[loc]||'').trim();if(!address)continue;if(/^M\d/i.test(address))marketplace=true;const code=r[sku]?String(r[sku]).trim().replace(/\.0+$/,''):null;rows.push({id:'base-'+(i+1),source_row:i+1,source_sheet:'Base Ruas',area:marketplace?'Marketplace':'Regulador',address,sku_code:code,sku_name:code?String(r[prod]||''):'',received_on:iso(r[rec],i+1),expires_on:iso(r[exp],i+1),pallets:r[qty]==null||r[qty]===''?null:Number(String(r[qty]).replace(',','.')),lock:String(r[lock]||''),inventory_confirmed:true});}
  const cold=wb.Sheets.Chopp;if(cold)for(const c of ['C','F'])for(let row=4;row<=10;row++){const cell=c+row,code=cold[cell]?.v;rows.push({id:'chopp-'+cell,source_row:row,source_sheet:'Chopp',area:'Câmara Fria',address:cell,sku_code:code?String(code):null,sku_name:code==='838'||code===838?'CHOPP BRAHMA CLARO BARRIL KEG 50L':'',received_on:null,expires_on:null,pallets:null,lock:'',inventory_confirmed:false});}
  const p=structuredClone(S.data.snapshot.payload);p.rows=rows;p.source_name=name;p.as_of=iso(wb.Sheets[sheetName].I4?.v,4)||new Date().toISOString().slice(0,10);core.validateSnapshot(p);return p;
 }
 async function mount(){
  const layout=$('layoutView'),tabs=layout?.querySelector('.layout-tabs');if(!tabs)return setTimeout(mount,100);
  core=await import('./stock-core.js?v=20260916-1');
  const style=document.createElement('link');style.rel='stylesheet';style.href='stock-module.css?v=20260916-1';document.head.appendChild(style);
  const panel=document.createElement('section');panel.id='stockLayoutPanel';panel.className='layout-section hidden';panel.dataset.layoutPanel='stock';layout.querySelector('.layout-module').appendChild(panel);
  for(const area of core.AREAS){const b=document.createElement('button');b.className='layout-tab';b.dataset.layoutTab='stock-'+area;b.dataset.stockArea=area;b.textContent=areaName(area);b.onclick=()=>openArea(area);tabs.appendChild(b);}
  tabs.querySelector('[data-layout-tab="picking"]').addEventListener('click',()=>{S.active='';document.querySelectorAll('[data-layout-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.layoutPanel!=='picking'));tabs.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.layoutTab==='picking'));window.__pickingLayout?.open();});
  const nav=document.createElement('button');nav.className='nav-link';nav.dataset.view='replenishment';nav.innerHTML='<span>↻</span> Reabastecimento';nav.onclick=()=>openFefo();document.querySelector('[data-view="layout"]').insertAdjacentElement('afterend',nav);
  const view=document.createElement('section');view.id='replenishmentView';view.className='view hidden';layout.insertAdjacentElement('afterend',view);
  for(const name of ['abc','layout'])document.querySelector('[data-view="'+name+'"]').addEventListener('click',()=>{view.classList.add('hidden');S.active='';if(name==='layout'){panel.classList.add('hidden');document.querySelector('[data-layout-panel="picking"]').classList.remove('hidden');tabs.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.layoutTab==='picking'));}});
  const adherence=document.createElement('details');adherence.className='panel stock-adherence';adherence.innerHTML='<summary>Aderência do estoque à Curva ABC</summary><div id="stockAdherenceBody"></div>';const abcAnchor=$('abcView').querySelector('.abc-layout');if(abcAnchor)abcAnchor.before(adherence);else $('abcView').appendChild(adherence);adherence.ontoggle=()=>{if(adherence.open)openAdherence();};
  const previous=renderCurve;renderCurve=function(){previous();if(adherence.open)openAdherence();};
  const originalApi=api;api=async function(action,payload={},auth=true){const result=await originalApi(action,payload,auth);if(['import','marketplace_import'].includes(action))S.data=null;return result;};
  window.__stockModule={refresh,openArea,openFefo};
 }
 setTimeout(mount,50);
})();
