(() => {
 const API='https://wzawtpadchtnvtclyghm.supabase.co/functions/v1/stock-api';
 const S={data:null,month:state.currentMonth,area:'Regulador',query:'',mode:'map',active:'',request:0,fefoCodes:'',origin:'Regulador',stockQuery:'',stockArea:''};
 let core;
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
 const nf=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2});
 const dt=x=>x?String(x).slice(0,10).split('-').reverse().join('/'):'Não informada';
 const norm=x=>String(x||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const areaName=a=>a==='Regulador'?'Estoque geral':a;
 const canEdit=()=>['admin','conferente'].includes(String(state.user?.role||'').toLowerCase());
 const badge=c=>`<span class="stock-badge ${['A','B','C'].includes(c)?c.toLowerCase():'unknown'}">${esc(c||'Sem curva')}</span>`;
 const table=(heads,rows)=>`<div class="stock-table-wrap"><table><thead><tr>${heads.map(h=>'<th>'+h+'</th>').join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
 async function call(action,payload={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','x-session-token':state.token},body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({error:'Resposta inválida'}));if(!r.ok)throw new Error(d.error||'Falha ao consultar estoque');return d;}
 async function load(force=false){if(!force&&S.data?.month===S.month)return S.data;const request=++S.request,data=await call('get',{month:S.month});if(request!==S.request)return null;S.data={...data,month:S.month};return S.data;}
 const meta=()=>S.data?.snapshot?`Base de ${dt(S.data.snapshot.as_of)} · Curva ABC ${S.month.split('-').reverse().join('/')} · última atualização do estoque`:'Nenhuma base importada';
 const matches=r=>!S.query||norm([r.address,r.sku_code,r.sku_name].join(' ')).includes(norm(S.query));
 const actions=()=>`<button class="outline-button" data-refresh>Atualizar consulta</button>${state.user?.role==='admin'?'<button class="primary-button" data-import>Importar estoque</button>':''}`;
 function bindActions(root){root.querySelector('[data-refresh]')?.addEventListener('click',refresh);root.querySelector('[data-import]')?.addEventListener('click',openImport);}
 async function refresh(){try{await load(true);renderActive();showToast('Consulta atualizada.');}catch(e){showToast(e.message,true);}}
 function hideViews(){document.querySelectorAll('main > .view').forEach(x=>x.classList.add('hidden'));document.querySelectorAll('.nav-link').forEach(x=>x.classList.remove('active'));$('sidebar')?.classList.remove('open');}
 function renderActive(){if(S.active==='layout')renderLayout();if(S.active==='fefo')renderFefo();if(S.active==='stock')renderStockBase();if(!$('abcView').classList.contains('hidden'))renderAdherence();}
 function openArea(area){S.active='layout';S.area=area;hideViews();$('layoutView').classList.remove('hidden');$('layoutView').classList.add('stock-area-active');document.querySelector('[data-view="layout"]')?.classList.add('active');$('pageTitle').textContent='Layout';$('pageSubtitle').textContent='Áreas físicas e estoque por endereço.';document.querySelectorAll('[data-layout-panel]').forEach(x=>x.classList.add('hidden'));document.querySelectorAll('[data-layout-tab]').forEach(x=>x.classList.toggle('active',x.dataset.stockArea===area));$('stockLayoutPanel').classList.remove('hidden');$('stockLayoutPanel').innerHTML='<p class="stock-empty">Carregando estoque…</p>';load().then(renderLayout).catch(e=>$('stockLayoutPanel').innerHTML=`<p class="stock-error">${esc(e.message)}</p>`);}
 function openFefo(codes='',area='Regulador'){S.active='fefo';if(codes)S.fefoCodes=String(codes);S.origin=area||S.origin;hideViews();$('replenishmentView').classList.remove('hidden');document.querySelector('[data-view="replenishment"]')?.classList.add('active');$('pageTitle').textContent='Reabastecimento';$('pageSubtitle').textContent='FEFO em lote para vários produtos.';$('replenishmentView').innerHTML='<p class="stock-empty">Carregando estoque…</p>';load().then(renderFefo).catch(e=>$('replenishmentView').innerHTML=`<p class="stock-error">${esc(e.message)}</p>`);}
 function openStockBase(){S.active='stock';hideViews();$('stockBaseView').classList.remove('hidden');document.querySelector('[data-view="stock-base"]')?.classList.add('active');$('pageTitle').textContent='Estoque x Estoque';$('pageSubtitle').textContent='Base Ruas operacional com rastreabilidade por usuário.';$('stockBaseView').innerHTML='<p class="stock-empty">Carregando Base Ruas…</p>';load().then(renderStockBase).catch(e=>$('stockBaseView').innerHTML=`<p class="stock-error">${esc(e.message)}</p>`);}
 function renderLayout(){
  if(S.active!=='layout')return;
  const root=$('stockLayoutPanel'),d=S.data;
  if(!d?.snapshot){root.innerHTML='<p class="stock-empty">Nenhuma base importada.</p>';return;}
  const locs=d.locations.filter(l=>l.area===S.area),rows=d.rows.filter(r=>r.area===S.area&&r.sku_code),known=rows.reduce((s,r)=>s+(r.pallets||0),0);
  const summary=`<div class="stock-summary-strip"><div><span><b>${locs.filter(l=>l.occupied).length}</b>/${locs.length} ocupados</span><span><b>${new Set(rows.map(r=>r.sku_code)).size}</b> SKUs</span><span><b>${nf.format(known)}</b> paletes</span><span><b>${rows.filter(r=>!r.expires_on).length}</b> sem validade</span></div><div class="stock-legend">${badge('A')} ${badge('B')} ${badge('C')} ${badge('Mista')}</div></div>`;
  const areaTabs=`<nav class="stock-area-tabs" aria-label="Áreas do armazém"><button data-compact-picking>Picking</button>${core.AREAS.map(area=>`<button class="${area===S.area?'active':''}" data-compact-area="${esc(area)}">${esc(areaName(area))}</button>`).join('')}</nav>`;
  root.innerHTML=`<div class="stock-module compact-layout"><section class="stock-control-panel">${areaTabs}<div class="stock-control-head"><p>${esc(meta())}</p><div class="stock-actions">${actions()}</div></div><div class="stock-control-row"><label>Curva ABC<select id="stockMonth">${MONTHS.map(([k,l])=>`<option value="${k}" ${k===S.month?'selected':''}>${l}/2026</option>`).join('')}</select></label><label class="stock-search">Localizar<input id="stockSearch" value="${esc(S.query)}" placeholder="Código, produto ou endereço"/></label><div class="stock-view-toggle"><button id="stockMapToggle" class="${S.mode==='map'?'active':''}">Mapa</button><button id="stockListToggle" class="${S.mode==='list'?'active':''}">Base de ruas</button></div></div>${summary}</section><div id="stockMapContent"></div><div id="stockLocationDetails"></div></div>`;
  bindActions(root);
  root.querySelector('[data-compact-picking]').onclick=()=>document.querySelector('[data-layout-tab="picking"]').click();
  root.querySelectorAll('[data-compact-area]').forEach(button=>button.onclick=()=>openArea(button.dataset.compactArea));
  $('stockMonth').onchange=async e=>{S.month=e.target.value;await load();renderLayout();};
  $('stockSearch').oninput=e=>{S.query=e.target.value;renderMapContent();};
  $('stockMapToggle').onclick=()=>{S.mode='map';renderLayout();};
  $('stockListToggle').onclick=()=>{S.mode='list';renderLayout();};
  renderMapContent();
 }
 function locationButton(loc,label,style=''){const codes=[...new Set((loc?.rows||[]).filter(r=>r.sku_code).map(r=>r.sku_code))];return `<button class="stock-cell ${loc?.occupied?'occupied':''} ${['A','B','C'].includes(loc?.curve)?loc.curve.toLowerCase():'unknown'} ${S.query&&(!loc||!loc.rows.some(matches))?'muted':''}" style="${style}" data-location="${esc(loc?.key||'')}" title="${esc(label+' · '+codes.join(', '))}"><strong>${esc(label)}</strong><span>${codes.length>1?codes.length+' SKUs':codes[0]||(loc?'Vazio':'Sem base')}</span></button>`;}
 function renderMapContent(){
  const root=$('stockMapContent'),d=S.data,locs=d.locations.filter(l=>l.area===S.area),byKey=new Map(locs.map(l=>[l.key,l]));
  if(S.mode==='list'){
   const rows=d.rows.filter(r=>r.area===S.area&&matches(r));
   root.innerHTML=table(['Endereço','Código / produto','Curva','Recebimento','Validade','Paletes','Situação',''],rows.map(r=>`<tr><td><button class="stock-link" data-location="${esc(core.keyOf(r))}">${esc(r.address)}</button></td><td><strong>${esc(r.sku_code||'Vazio')}</strong><small>${esc(r.sku_name)}</small></td><td>${badge(r.curve)}</td><td>${dt(r.received_on)}</td><td>${dt(r.expires_on)}</td><td>${r.pallets==null?'—':nf.format(r.pallets)}</td><td>${esc(r.fefo_status)}</td><td>${canEdit()?`<button class="stock-link" data-edit="${esc(r.id)}">Editar</button>`:''}</td></tr>`));
  }else{
   const anchors=d.snapshot.payload.maps[S.area]?.anchors||[];
   if(!anchors.length){root.innerHTML='<p class="stock-empty">Sem mapa cadastrado para esta área.</p>';return;}
   const mapped=new Set(anchors.map(a=>S.area+':'+core.normalizeAddress(a.address)));
   const minC=Math.min(...anchors.map(a=>a.col)),minR=Math.min(...anchors.map(a=>a.row));
   const maxC=Math.max(...anchors.map(a=>a.col+(a.width||1)-1)),maxR=Math.max(...anchors.map(a=>a.row+(a.height||1)-1));
   const unit=S.area==='Regulador'?58:68,rh=S.area==='Regulador'?32:52,compact=S.area==='Regulador';
   const compactAxis=(start,size,minimum,maximum)=>{
    if(!compact)return {at:value=>value-minimum,span:(_value,length)=>length,extent:maximum-minimum+2};
    const used=new Set();
    anchors.forEach(anchor=>{const first=anchor[start],length=anchor[size]||1;for(let i=0;i<length;i++)used.add(first+i);});
    const values=[...used].sort((a,b)=>a-b),positions=new Map();let position=0;
    values.forEach((value,index)=>{if(index)position+=value-values[index-1]===1?1:1.08;positions.set(value,position);});
    return {at:value=>positions.get(value)||0,span:(value,length)=>(positions.get(value+length-1)-positions.get(value))+1,extent:position+2};
   };
   const cols=compactAxis('col','width',minC,maxC),rows=compactAxis('row','height',minR,maxR);
   const mapWidth=cols.extent*unit,mapHeight=rows.extent*rh;
   const cells=anchors.map(a=>locationButton(byKey.get(S.area+':'+core.normalizeAddress(a.address)),a.address,`left:${cols.at(a.col)*unit}px;top:${rows.at(a.row)*rh}px;width:${cols.span(a.col,a.width||1)*unit-3}px;height:${rows.span(a.row,a.height||1)*rh-4}px`)).join('');
   const zoomControls=compact?'':`<div class="stock-map-zoom" role="group" aria-label="Ampliação do mapa"><button class="active" data-map-zoom="fit">Ver tudo</button><button data-map-zoom="0.5">50%</button><button data-map-zoom="0.75">75%</button><button data-map-zoom="1">100%</button></div>`;
   root.innerHTML=`<div class="stock-map-header"><div><strong>${compact?'Croqui do Regulador':'Visão da área'}</strong><span>${compact?'Visão simples e completa':'Mapa ajustado automaticamente à tela'}</span></div>${zoomControls}</div>${compact?'<div class="stock-flow-direction"><span>REGULADOR</span><i></i><strong>REDZONE • PICKING →</strong></div>':''}<div class="stock-map-scroll fit ${compact?'mini':''}"><div class="stock-map-stage"><div class="stock-map" style="width:${mapWidth}px;height:${mapHeight}px">${cells}</div></div></div>`;
   const scroll=root.querySelector('.stock-map-scroll'),stage=root.querySelector('.stock-map-stage'),map=root.querySelector('.stock-map');let zoomMode='fit';
   const applyZoom=()=>{const widthFit=(scroll.clientWidth-20)/mapWidth,fit=compact?Math.min(1.35,Math.max(.2,widthFit)):Math.min(1,Math.max(.04,widthFit)),scale=zoomMode==='fit'?fit:Number(zoomMode);map.style.transform=`scale(${scale})`;stage.style.width=`${mapWidth*scale}px`;stage.style.height=`${mapHeight*scale}px`;scroll.classList.toggle('fit',zoomMode==='fit');root.querySelectorAll('[data-map-zoom]').forEach(b=>b.classList.toggle('active',b.dataset.mapZoom===zoomMode));};
   root.querySelectorAll('[data-map-zoom]').forEach(b=>b.onclick=()=>{zoomMode=b.dataset.mapZoom;applyZoom();});
   applyZoom();
   if(window.ResizeObserver)new ResizeObserver(()=>zoomMode==='fit'&&applyZoom()).observe(scroll);
   const extras=locs.filter(l=>!mapped.has(l.key));
   if(extras.length)root.insertAdjacentHTML('beforeend',`<details class="stock-unmapped"><summary>${extras.length} endereços fora do desenho</summary><div class="stock-extra-grid">${extras.map(l=>locationButton(l,l.address)).join('')}</div></details>`);
  }
  root.querySelectorAll('[data-location]').forEach(b=>b.onclick=()=>showLocation(b.dataset.location));
  root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editRow(b.dataset.edit));
 }
 function showLocation(key){const loc=S.data.locations.find(l=>l.key===key);if(!loc){showToast('Endereço sem registro.',true);return;}const root=$('stockLocationDetails');root.innerHTML=`<article class="panel stock-details"><div class="stock-heading"><h3>${esc(areaName(loc.area))} · ${esc(loc.address)}</h3><button class="outline-button" id="stockDetailClose">Fechar</button></div>${table(['Produto','Validade','Paletes','FEFO',''],loc.rows.map(r=>`<tr><td><strong>${esc(r.sku_code||'Vazio')}</strong><small>${esc(r.sku_name)}</small></td><td>${dt(r.expires_on)}</td><td>${r.pallets==null?'—':nf.format(r.pallets)}</td><td>${esc(r.fefo_status)}</td><td>${r.sku_code?`<button class="stock-link" data-fefo="${esc(r.sku_code)}">FEFO</button>`:''} ${canEdit()?`<button class="stock-link" data-edit="${esc(r.id)}">Editar</button>`:''}</td></tr>`))}</article>`;$('stockDetailClose').onclick=()=>root.innerHTML='';root.querySelectorAll('[data-fefo]').forEach(b=>b.onclick=()=>openFefo(b.dataset.fefo,loc.area));root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editRow(b.dataset.edit));}
 function parseCodes(text){return [...new Set(String(text||'').split(/[\s,;|]+/).map(x=>x.trim()).filter(x=>/^\d+$/.test(x)))];}
 function renderFefo(){
  if(S.active!=='fefo')return;const root=$('replenishmentView');if(!S.data?.snapshot){root.innerHTML='<p class="stock-empty">Nenhuma base importada.</p>';return;}
  root.innerHTML=`<div class="stock-module"><div class="stock-heading"><div><p class="eyebrow">ESTOQUE → PICKING</p><h2>Reabastecimento FEFO em lote</h2><p>${esc(meta())}</p></div><div class="stock-actions">${actions()}</div></div><div class="stock-toolbar"><label class="stock-search">Produtos<textarea id="fefoSkus" rows="3" placeholder="Cole vários códigos separados por espaço, vírgula ou linha">${esc(S.fefoCodes)}</textarea></label><label>Área de origem<select id="fefoArea">${core.AREAS.map(a=>`<option ${a===S.origin?'selected':''}>${esc(a)}</option>`).join('')}</select></label><button class="primary-button" id="fefoConsult">Consultar todos</button></div><p class="stock-help">A consulta retorna todos os SKUs de uma vez, já ordenados por FEFO. Você pode colar uma relação inteira de códigos.</p><div id="fefoResult"></div><details class="stock-method"><summary>Critérios de consumo</summary><p>Primeiro vence, primeiro sai. Validade é o critério principal; recebimento e endereço desempatarão. Lotes vencidos, vencendo hoje, sem validade, com trava-palete ou inconsistência não são recomendados.</p></details></div>`;
  bindActions(root);$('fefoConsult').onclick=()=>{S.fefoCodes=$('fefoSkus').value;S.origin=$('fefoArea').value;renderFefoResult();};$('fefoArea').onchange=()=>{S.origin=$('fefoArea').value;renderFefoResult();};renderFefoResult();
 }
 function renderFefoResult(){
  const root=$('fefoResult'),codes=parseCodes(S.fefoCodes);if(!codes.length){root.innerHTML='<div class="stock-empty">Cole ou digite os códigos que deseja consultar.</div>';return;}
  const groups=codes.map(code=>{const rows=core.fefoRows(S.data.rows,code,S.origin),ready=rows.filter(r=>['Prioridade FEFO','Aguardar lote anterior'].includes(r.fefo_status)),first=ready[0],dates=[...new Set(ready.map(r=>r.expires_on))];return{code,rows,ready,first,dates};});
  root.innerHTML=`<div class="stock-kpis"><article><small>Produtos consultados</small><strong>${codes.length}</strong></article><article><small>Com lote disponível</small><strong>${groups.filter(g=>g.first).length}</strong></article><article><small>Sem lote recomendado</small><strong>${groups.filter(g=>!g.first).length}</strong></article><article><small>Lotes encontrados</small><strong>${groups.reduce((s,g)=>s+g.rows.length,0)}</strong></article></div>`+groups.map(g=>`<details class="stock-method" ${g.first?'open':''}><summary><strong>${esc(g.code)}</strong> · ${esc(g.rows[0]?.sku_name||'Produto não encontrado')} · ${g.first?`consumir ${esc([...new Set(g.ready.filter(r=>r.expires_on===g.first.expires_on).map(r=>r.address))].join(' / '))} (${dt(g.first.expires_on)})`:'sem lote recomendado'}</summary>${g.rows.length?table(['Prioridade','Endereço','Recebimento','Validade','Dias','Paletes','Condição',''],g.rows.map(r=>`<tr><td>${['Prioridade FEFO','Aguardar lote anterior'].includes(r.fefo_status)?g.dates.indexOf(r.expires_on)+1:'—'}</td><td><strong>${esc(r.address)}</strong></td><td>${dt(r.received_on)}</td><td>${dt(r.expires_on)}</td><td>${r.days??'—'}</td><td>${r.pallets==null?'Conferir saldo':nf.format(r.pallets)}</td><td>${esc(r.fefo_status)}</td><td><button class="stock-link" data-map="${esc(r.address)}">Ver layout</button></td></tr>`)):'<p class="stock-empty">Código não localizado nesta área.</p>'}</details>`).join('');
  root.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>{S.query=b.dataset.map;openArea(S.origin);});
 }
 function stockRows(){return (S.data?.rows||[]).filter(r=>r.source_sheet==='Base Ruas'&&(!S.stockArea||r.area===S.stockArea)&&(!S.stockQuery||norm([r.address,r.sku_code,r.sku_name,r.received_on,r.expires_on,r.lock].join(' ')).includes(norm(S.stockQuery))));}
 async function renderStockBase(){
  if(S.active!=='stock')return;const root=$('stockBaseView');if(!S.data?.snapshot){root.innerHTML='<p class="stock-empty">Nenhuma Base Ruas importada.</p>';return;}const rows=stockRows(),occupied=rows.filter(r=>r.sku_code),history=await call('history',{limit:50}).catch(()=>({items:[]}));
  root.innerHTML=`<div class="stock-module"><div class="stock-heading"><div><p class="eyebrow">BASE RUAS</p><h2>Estoque x Estoque</h2><p>${esc(meta())}</p></div><div class="stock-actions">${actions()}</div></div><div class="stock-toolbar"><label>Área<select id="baseArea"><option value="">Todas</option><option value="Regulador" ${S.stockArea==='Regulador'?'selected':''}>Estoque geral</option><option value="Marketplace" ${S.stockArea==='Marketplace'?'selected':''}>Marketplace</option></select></label><label class="stock-search">Pesquisar<input id="baseSearch" value="${esc(S.stockQuery)}" placeholder="Rua, código, produto, validade..."/></label></div><div class="stock-kpis"><article><small>Linhas da Base Ruas</small><strong>${rows.length}</strong></article><article><small>Com produto</small><strong>${occupied.length}</strong></article><article><small>Sem validade</small><strong>${occupied.filter(r=>!r.expires_on).length}</strong></article><article><small>Últimas alterações</small><strong>${history.items.length}</strong><span>rastreio de usuário ativo</span></article></div><section class="panel"><div class="panel-heading"><h2>Base Ruas</h2><small>${canEdit()?'Clique em Editar para alimentar a base pelo site.':'Visualização'}</small></div>${table(['Rua','Código / produto','Recebimento','Validade','Paletes','Trava-palete',''],rows.map(r=>`<tr><td><strong>${esc(r.address)}</strong><small>${esc(areaName(r.area))}</small></td><td><strong>${esc(r.sku_code||'Vazio')}</strong><small>${esc(r.sku_name||'')}</small></td><td>${dt(r.received_on)}</td><td>${dt(r.expires_on)}</td><td>${r.pallets==null?'—':nf.format(r.pallets)}</td><td>${esc(r.lock||'—')}</td><td>${canEdit()?`<button class="stock-link" data-edit="${esc(r.id)}">Editar</button>`:''}</td></tr>`))}</section><details class="panel stock-method"><summary>Histórico de alterações</summary><div class="stock-audit-list">${history.items.length?history.items.map(h=>{const u=h.app_users?.display_name||h.app_users?.username||'Usuário';const action=h.action==='IMPORT'?'Importação':h.action==='BULK_EDIT'?'Edição em lote':'Edição';return `<div class="stock-audit-row"><strong>${esc(u)}</strong><span>${esc(action)} · ${h.changed_count} registro(s)</span><small>${new Date(h.created_at).toLocaleString('pt-BR')} · ${esc(h.note||'')}</small></div>`;}).join(''):'<p class="stock-empty">Nenhuma alteração registrada após a ativação do rastreio.</p>'}</div></details></div>`;
  bindActions(root);$('baseArea').onchange=e=>{S.stockArea=e.target.value;renderStockBase();};let t;$('baseSearch').oninput=e=>{S.stockQuery=e.target.value;clearTimeout(t);t=setTimeout(renderStockBase,120);};root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editRow(b.dataset.edit));
 }
 async function openAdherence(){S.month=state.currentMonth;const root=$('stockAdherenceBody');root.innerHTML='<p class="stock-empty">Cruzando estoque com Curva ABC…</p>';try{await load();renderAdherence();}catch(e){root.innerHTML=`<p class="stock-error">${esc(e.message)}</p>`;}}
 function renderAdherence(){const root=$('stockAdherenceBody');if(!root||!S.data?.snapshot)return;root.innerHTML=`<p class="stock-help">${esc(meta())}. Estoque atual comparado à curva do mês selecionado.</p><div class="stock-adherence-cards">${S.data.adherence.map(a=>`<article><small>${esc(areaName(a.area))}</small><strong>${a.rate===null?'—':nf.format(a.rate*100)+'%'}</strong><p>${a.real} posições A / meta ${a.planned}</p><span>${a.monitored} endereços monitorados</span></article>`).join('')}</div>`;}
 function dialog(title,body){$('stockDialog')?.remove();const d=document.createElement('dialog');d.id='stockDialog';d.className='stock-dialog';d.innerHTML=`<div class="stock-heading"><h2>${esc(title)}</h2><button class="outline-button" id="stockDialogClose">Fechar</button></div>${body}<p class="stock-error" id="stockDialogError"></p>`;document.body.appendChild(d);$('stockDialogClose').onclick=()=>d.close();d.showModal();return d;}
 async function save(payload,opts={}){const result=await call('save',{previous_id:S.data.snapshot.id,payload,change_type:opts.change_type||'EDIT',note:opts.note||''});S.data=null;await load(true);renderActive();return result;}
 function editRow(id){
  const row=S.data?.rows?.find(r=>r.id===id);if(!row||!canEdit())return;const d=dialog('Atualizar Base Ruas',`<p><strong>${esc(row.address)}</strong> · ${esc(areaName(row.area))}</p><form id="stockEditForm" class="stock-form"><label>Código<input name="sku_code" value="${esc(row.sku_code||'')}" pattern="[0-9]*"/></label><label>Produto<input name="sku_name" value="${esc(row.sku_name)}"/></label><label>Recebimento<input name="received_on" type="date" value="${esc(row.received_on||'')}"/></label><label>Validade<input name="expires_on" type="date" value="${esc(row.expires_on||'')}"/></label><label>Quantidade (paletes)<input name="pallets" type="number" min="0" step="any" value="${row.pallets??''}"/></label><label>Trava-palete / motivo<input name="lock" value="${esc(row.lock)}"/></label><label>Observação da alteração<input name="note" placeholder="Ex.: conferência física / ajuste de validade"/></label><button class="primary-button" type="submit">Salvar atualização</button></form>`);
  $('stockEditForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const f=Object.fromEntries(new FormData(e.target)),p=structuredClone(S.data.snapshot.payload),r=p.rows.find(x=>x.id===id);Object.assign(r,{sku_code:f.sku_code||null,sku_name:f.sku_name,received_on:f.received_on||null,expires_on:f.expires_on||null,pallets:f.pallets===''?null:Number(f.pallets),lock:f.lock,inventory_confirmed:true});p.source_name='Atualização no painel';await save(p,{change_type:'EDIT',note:f.note||`Atualização ${row.address}`});d.close();showToast('Base Ruas atualizada e alteração registrada.');}catch(err){$('stockDialogError').textContent=err.message;}finally{b.disabled=false;}};
 }
 async function openImport(){
  if(state.user?.role!=='admin')return;const d=dialog('Importar Estoque x Estoque',`<p>A importação substitui a fotografia ativa da Base Ruas e preserva a anterior no histórico.</p><div class="stock-form"><label>Planilha<input id="stockFile" type="file" accept=".xlsx"/></label><label>Data de referência<input id="stockAsOf" type="date" value="${esc(S.data?.snapshot?.as_of||new Date().toISOString().slice(0,10))}"/></label></div><div id="stockImportPreview"></div><button class="primary-button" id="stockImportConfirm" disabled>Publicar base</button>`);let pending;
  $('stockFile').onchange=async e=>{pending=null;$('stockImportConfirm').disabled=true;const file=e.target.files[0];if(!file)return;try{$('stockImportPreview').textContent='Lendo Base Ruas…';if(!window.XLSX)await readRows(file);const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});pending=parseWorkbook(wb,file.name);$('stockAsOf').value=pending.as_of;$('stockImportPreview').innerHTML=`<p>${pending.rows.filter(r=>r.source_sheet==='Base Ruas').length} linhas da Base Ruas.</p>`;$('stockImportConfirm').disabled=false;}catch(err){$('stockDialogError').textContent=err.message;}};
  $('stockImportConfirm').onclick=async()=>{const b=$('stockImportConfirm');b.disabled=true;try{pending.as_of=$('stockAsOf').value;core.validateSnapshot(pending);await save(pending,{change_type:'IMPORT',note:`Importação ${pending.source_name}`});d.close();showToast('Base integrada atualizada e importação registrada.');}catch(err){$('stockDialogError').textContent=err.message;}finally{b.disabled=false;}};
 }
 function parseWorkbook(wb,name){
  const sheetName=wb.SheetNames.find(n=>norm(n)==='base ruas');if(!sheetName)throw new Error('Aba Base Ruas não encontrada.');const data=XLSX.utils.sheet_to_json(wb.Sheets[sheetName],{header:1,raw:true,defval:null});const head=data.findIndex(r=>r.some(x=>norm(x)==='rua')&&r.some(x=>norm(x)==='validade'));if(head<0)throw new Error('Cabeçalhos da Base Ruas não encontrados.');const headers=data[head].map(norm),col=n=>headers.indexOf(n),loc=col('rua'),sku=col('codigo'),prod=col('produto'),rec=col('recebimento'),exp=col('validade'),qty=col('quantidade (plt)'),lock=col('trava-palete');if([loc,sku,rec,exp,qty].some(i=>i<0))throw new Error('Colunas obrigatórias ausentes.');const iso=(x,line)=>{if(x==null||x==='')return null;if(x instanceof Date)return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`;if(typeof x==='number'){const z=XLSX.SSF.parse_date_code(x);return z?`${z.y}-${String(z.m).padStart(2,'0')}-${String(z.d).padStart(2,'0')}`:null;}const m=String(x).match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;if(/^\d{4}-\d{2}-\d{2}$/.test(String(x)))return String(x);throw new Error('Data inválida na linha '+line);};let marketplace=false;const rows=[];for(let i=head+1;i<data.length;i++){const r=data[i],address=String(r[loc]||'').trim();if(!address)continue;if(/^M\d/i.test(address))marketplace=true;const code=r[sku]?String(r[sku]).trim().replace(/\.0+$/,''):null;rows.push({id:'base-'+(i+1),source_row:i+1,source_sheet:'Base Ruas',area:marketplace?'Marketplace':'Regulador',address,sku_code:code,sku_name:code?String(r[prod]||''):'',received_on:iso(r[rec],i+1),expires_on:iso(r[exp],i+1),pallets:r[qty]==null||r[qty]===''?null:Number(String(r[qty]).replace(',','.')),lock:String(r[lock]||''),inventory_confirmed:true});}const cold=wb.Sheets.Chopp;if(cold)for(const c of ['C','F'])for(let row=4;row<=10;row++){const cell=c+row,code=cold[cell]?.v;rows.push({id:'chopp-'+cell,source_row:row,source_sheet:'Chopp',area:'Câmara Fria',address:cell,sku_code:code?String(code):null,sku_name:code==='838'||code===838?'CHOPP BRAHMA CLARO BARRIL KEG 50L':'',received_on:null,expires_on:null,pallets:null,lock:'',inventory_confirmed:false});}const p=structuredClone(S.data.snapshot.payload);p.rows=rows;p.source_name=name;p.as_of=iso(wb.Sheets[sheetName].I4?.v,4)||new Date().toISOString().slice(0,10);core.validateSnapshot(p);return p;
 }
 async function mount(){
  const layout=$('layoutView'),tabs=layout?.querySelector('.layout-tabs');if(!tabs)return setTimeout(mount,100);core=await import('./stock-core.js?v=20260916-2');const style=document.createElement('link');style.rel='stylesheet';style.href='stock-module.css?v=20260916-2';document.head.appendChild(style);const panel=document.createElement('section');panel.id='stockLayoutPanel';panel.className='layout-section hidden';panel.dataset.layoutPanel='stock';layout.querySelector('.layout-module').appendChild(panel);for(const area of core.AREAS){const b=document.createElement('button');b.className='layout-tab';b.dataset.layoutTab='stock-'+area;b.dataset.stockArea=area;b.textContent=areaName(area);b.onclick=()=>openArea(area);tabs.appendChild(b);}tabs.querySelector('[data-layout-tab="picking"]').addEventListener('click',()=>{S.active='';layout.classList.remove('stock-area-active');document.querySelectorAll('[data-layout-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.layoutPanel!=='picking'));tabs.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.layoutTab==='picking'));window.__pickingLayout?.open();});
  const stockNav=document.createElement('button');stockNav.className='nav-link';stockNav.dataset.view='stock-base';stockNav.innerHTML='<span>▦</span> Estoque x Estoque';stockNav.onclick=openStockBase;document.querySelector('[data-view="layout"]').insertAdjacentElement('afterend',stockNav);const nav=document.createElement('button');nav.className='nav-link';nav.dataset.view='replenishment';nav.innerHTML='<span>↻</span> Reabastecimento';nav.onclick=()=>openFefo();stockNav.insertAdjacentElement('afterend',nav);
  const stockView=document.createElement('section');stockView.id='stockBaseView';stockView.className='view hidden';layout.insertAdjacentElement('afterend',stockView);const view=document.createElement('section');view.id='replenishmentView';view.className='view hidden';stockView.insertAdjacentElement('afterend',view);
  for(const name of ['abc','layout'])document.querySelector('[data-view="'+name+'"]').addEventListener('click',()=>{stockView.classList.add('hidden');view.classList.add('hidden');layout.classList.remove('stock-area-active');S.active='';if(name==='layout'){panel.classList.add('hidden');document.querySelector('[data-layout-panel="picking"]').classList.remove('hidden');tabs.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.layoutTab==='picking'));}});
  const adherence=document.createElement('details');adherence.className='panel stock-adherence';adherence.innerHTML='<summary>Aderência do estoque à Curva ABC</summary><div id="stockAdherenceBody"></div>';const abcAnchor=$('abcView').querySelector('.abc-layout');if(abcAnchor)abcAnchor.before(adherence);else $('abcView').appendChild(adherence);adherence.ontoggle=()=>{if(adherence.open)openAdherence();};const previous=renderCurve;renderCurve=function(){previous();if(adherence.open)openAdherence();};const originalApi=api;api=async function(action,payload={},auth=true){const result=await originalApi(action,payload,auth);if(['import','marketplace_import'].includes(action))S.data=null;return result;};window.__stockModule={refresh,openArea,openFefo,openStockBase};
 }
 setTimeout(mount,50);
})();
