import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {summarizeWorkbook} from '../blitz-import-core.mjs';
function evaluate(data){const context=vm.createContext({window:{},document:{querySelector:()=>null}});vm.runInContext(fs.readFileSync(new URL('../blitz.js',import.meta.url),'utf8'),context);context.data=data;vm.runInContext('B.data=data',context);return {summary:JSON.parse(vm.runInContext('JSON.stringify(summary())',context)),charts:vm.runInContext('blitzCharts(summary())',context),table:vm.runInContext('JSON.stringify(reasonRows(summary()))',context)};}
const row={reference_date:'2026-09-01',trailer:'298',check_time:'14:00',checker:'Teste',quantity_units:8,reason:'Faltante',trips_day:6,trips_checked:2,packages_checked:4140};
test('occurrences count positive item lines while reason quantities sum units from historical and manual entries',()=>{const historical=[row,{...row,quantity_units:3,reason:'Sem Tampa'},{...row,quantity_units:0}],manual={...row,reference_date:'2026-09-02',quantity_units:5};const result=evaluate({cache:summarizeWorkbook(historical),workbook_rows:historical,checks:[{...manual,trips_day:4,trips_checked:1}],losses:[manual]});assert.equal(result.summary.lossLines,3);assert.equal(result.summary.units,16);assert.deepEqual(result.summary.byReasonCounts,{Faltante:2,'Sem Tampa':1});assert.equal(Object.values(result.summary.byReason).reduce((sum,n)=>sum+n,0),16);assert.equal(result.summary.daily.reduce((sum,d)=>sum+d.trips_day,0),10);assert.match(result.charts,/Viagens por dia/);assert.doesNotMatch(result.charts,/Sem viagens registradas por dia/);assert.match(result.charts,/Total: 3 ocorrências \/ 16 un/);assert.deepEqual(JSON.parse(result.table),[['Faltante','2','13 un'],['Sem Tampa','1','3 un']]);});
test('historical rows overridden by manual checks do not double count either units or occurrences',()=>{const historical=[row,{...row,quantity_units:3,reason:'Sem Tampa'}],manualCheck={...row},manualLoss={...row,quantity_units:6};const result=evaluate({cache:summarizeWorkbook(historical,[manualCheck]),workbook_rows:[],checks:[manualCheck],losses:[manualLoss]});assert.equal(result.summary.lossLines,1);assert.equal(result.summary.units,6);assert.deepEqual(result.summary.byReasonCounts,{Faltante:1});assert.equal(result.summary.tripsDay,6);});
