import test from 'node:test';import assert from 'node:assert/strict';import {webcrypto,pbkdf2Sync} from 'node:crypto';import {readFileSync} from 'node:fs';import {createPinRecord,verifyPinRecord} from '../supabase/functions/bo-api/pin-crypto.mjs';
const source=readFileSync(new URL('../supabase/functions/bo-api/index.ts',import.meta.url),'utf8');const start=source.indexOf('    if(action==="pin_login")'),end=source.indexOf('    if(["bo_session"',start);const handlerSource=source.slice(start,end);const AsyncFunction=Object.getPrototypeOf(async()=>{}).constructor;
const pin='012345',salt=Buffer.from('fixture-salt-123').toString('base64url');
function setup({legacy=false,error=null,cryptoError=false,locked=false,concurrentReset=false}={}){let row={id:'fixture-user',active:true,display_name:'Fixture',pin_salt:salt,pin_hash:'pbkdf2-sha256$200000$'+pbkdf2Sync(pin,legacy?Buffer.from(salt):Buffer.from(salt,'base64url'),200000,32,'sha256').toString('base64url'),failed_attempts:2,locked_until:locked?new Date(Date.now()+60000).toISOString():null};let updates=[],sessions=0;
const db={from(table){let mode='select',payload;const q={select(){return q},eq(){return q},lt(){return q},update(p){mode='update';payload=p;return q},delete(){mode='delete';return q},insert(){mode='insert';return q},maybeSingle(){return q},then(resolve,reject){let data=row,e=null;if(table==='bo_conferencers'){if(mode==='select')e=error;else if(mode==='update'){updates.push(payload);row={...row,...payload};data=concurrentReset?null:{id:row.id}}}else if(mode==='insert')sessions++;return Promise.resolve({data,error:e}).then(resolve,reject)}};return q}};
const context={db,cleanText:v=>String(v??'').trim(),MAX_PIN_ATTEMPTS:5,LOCK_MINUTES:15,PIN_SESSION_HOURS:8,verifyPinRecord:cryptoError?async()=>{throw Error('crypto unavailable')}:verifyPinRecord,pinRecord:createPinRecord,json:(_req,body,status=200)=>({body,status}),randomToken:()=> 'fixture-token',sha256:async()=> 'fixture-token-hash',console:{error(){},info(){}}};const fn=new AsyncFunction('action','body','req',...Object.keys(context),handlerSource);return {run:()=>fn('pin_login',{conferencer_id:row.id,pin},null,...Object.values(context)),state:()=>({row,updates,sessions})};}
test('legacy PIN login upgrades only validated credential and creates one session',async()=>{const x=setup({legacy:true});assert.equal((await x.run()).status,200);assert.equal(x.state().sessions,1);assert.equal((await verifyPinRecord(pin,x.state().row)).valid,true);assert.equal((await verifyPinRecord(pin,x.state().row)).legacy,false);assert.equal(x.state().row.failed_attempts,0);});
test('canonical login preserves credential hash and salt',async()=>{const x=setup();assert.equal((await x.run()).status,200);assert.equal(x.state().updates[0].pin_hash,undefined);assert.equal(x.state().updates[0].pin_salt,undefined);});
test('database and crypto failures return 503 without recording incorrect PIN attempts',async()=>{for(const options of [{error:{code:'database-error'}},{cryptoError:true}]){const x=setup(options);assert.equal((await x.run()).status,503);assert.equal(x.state().updates.length,0);assert.equal(x.state().sessions,0);}});
test('lockout and concurrent reset cannot mint sessions',async()=>{for(const [options,status] of [[{locked:true},429],[{concurrentReset:true},409]]){const x=setup(options);assert.equal((await x.run()).status,status);assert.equal(x.state().sessions,0);}});
