import test from 'node:test';
import assert from 'node:assert/strict';
import {hours,loadProfile,selectPeriod,weekStart,weeklySeries} from '../efc-analytics.mjs';
import {seriesChart,donutChart} from '../efc-charts.mjs';
test('histogram sums pallets rather than activity count and ignores invalid times',()=>{const h=hours([{end:'21:20',pallets:8},{end:'21:50',pallets:4},{end:null,pallets:20},{end:'oops',pallets:2},{end:'2026-09-02T00:10:00',pallets:7}], 'end','pallets');assert.equal(h.find(x=>x.hour===21).value,12);assert.equal(h.find(x=>x.hour===21).activities,2);assert.equal(h.find(x=>x.hour===0).value,7);assert.equal(h.reduce((a,x)=>a+x.value,0),19);});
test('profile marks missing reconciliation instead of assigning a band',()=>{const p=loadProfile([{boxes:100,pallets:2},{boxes:102,pallets:2},{boxes:null,pallets:3}]);assert.equal(p.bands[0].value,1);assert.equal(p.bands[1].value,1);assert.equal(p.missing,1);});
test('week selection excludes stale month rows while retaining events for overnight matching',()=>{const data={helpers:[{date:'2026-09-01'},{date:'2026-10-01'},{date:'2026-10-08'}],events:[{date:'2026-09-30'}],capacity:[{sku:1}]};const out=selectPeriod(data,'2026-10','',weekStart('2026-10-01'));assert.deepEqual(out.helpers,[{date:'2026-10-01'}]);assert.equal(out.events.length,1);assert.equal(out.capacity.length,1);});
test('weekly EFC weights vehicles rather than averaging daily rates',()=>{const c={loads:[{date:'2026-09-01',status:'on_time'},...Array.from({length:9},()=>({date:'2026-09-02',status:'late'}))],helpers:[],checkers:[],supply:[],errors:[]};assert.equal(weeklySeries(c)[0].efc,.1);});
test('chart leaves missing values absent and escapes source labels',()=>{const svg=seriesChart({id:'test',title:'<safe>',data:[{label:'1',value:75},{label:'2',value:null}],series:[{key:'value',label:'Rate'}],percent:true,goal:96,bars:true});assert.ok(svg.includes('&lt;safe&gt;'));assert.equal((svg.match(/data-chart-tip=/g)||[]).length,1);assert.ok(svg.includes('Meta 96%'));assert.ok(donutChart({id:'zero',title:'Zero',data:[{label:'a',value:0}]}).includes('Sem volume'));});
