import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {stripTypeScriptTypes} from 'node:module';import {webcrypto} from 'node:crypto';
function handler(role='admin',valid=true){let serve,mutations=0;const db={rpc(){mutations++;return Promise.resolve({data:null,error:null});},from(table){const q={select(){return q},eq(){return q},gt(){return q},gte(){return q},lt(){return q},order(){return q},range(){return Promise.resolve({data:table==='efc_archive'?[{kind:'helpers',source:'test.xlsx',payload:[{id:'2026-10:helpers:4',date:'2026-10-01',name:'A',map:'1',pallets:2}]}]:[],error:null});},single(){return Promise.resolve({data:{status:'completed'},error:null});},maybeSingle(){return Promise.resolve({data:table==='app_sessions'?(valid?{user_id:'test'}:null):table==='app_users'?{id:'test',role}:table==='receiving_pull_agent_nodes'?null:null,error:null});},update(){mutations++;return q;},upsert(){mutations++;return Promise.resolve({error:null});},then(fn){return Promise.resolve({data:table==='efc_archive'?[{payload:[{id:'2026-10:helpers:4'}]}]:[],error:null}).then(fn);}};return q;}};let src=fs.readFileSync(new URL('../supabase/functions/efc-api/index.ts',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace(/^const db=createClient.*;\n/m,'');src=stripTypeScriptTypes(src);vm.runInNewContext(src,{db,Deno:{serve:f=>serve=f},Request,Response,TextEncoder,crypto:webcrypto,btoa,console,Map,Date});return{serve,mutations:()=>mutations};}
const req=(b,t='test')=>new Request('https://test.invalid',{method:'POST',headers:{'Content-Type':'application/json',...(t?{'x-session-token':t}:{})},body:JSON.stringify({month:'2026-10',...b})});
test('EFC rejects unauthenticated and expired sessions',async()=>{assert.equal((await handler().serve(req({action:'dashboard'},''))).status,401);assert.equal((await handler('admin',false).serve(req({action:'dashboard'}))).status,401);});
test('EFC reader can consult private archive but cannot adjust',async()=>{const h=handler('viewer');const d=await h.serve(req({action:'dashboard'}));assert.equal(d.status,200);assert.equal((await d.json()).data.helpers.length,1);assert.equal((await h.serve(req({action:'adjust'}))).status,403);assert.equal(h.mutations(),0);});
test('EFC corrections require existing source row, reason and allowed fields',async()=>{const h=handler();for(const b of [{id:'2026-10:helpers:99',reason:'Correção',patch:{pallets:4}},{id:'2026-10:helpers:4',reason:'',patch:{pallets:4}},{id:'2026-10:helpers:4',reason:'Correção',patch:{cached_payment:999}},{id:'2026-10:helpers:4',reason:'Correção',patch:{pallets:-1}}])assert.ok((await h.serve(req({action:'adjust',kind:'helpers',...b}))).status>=400);assert.equal(h.mutations(),0);});
test('EFC valid correction uses atomic audit RPC',async()=>{const h=handler();assert.equal((await h.serve(req({action:'adjust',kind:'helpers',id:'2026-10:helpers:4',reason:'Pallets conferidos',patch:{pallets:4}}))).status,200);assert.equal(h.mutations(),1);});
test('Agent event ingestion cannot be called with a panel session',async()=>{assert.equal((await handler().serve(req({action:'agent_events',rows:[]}))).status,401);});
test('closed history cannot be silently changed by admin adjustments',async()=>{const h=handler();const r=await h.serve(req({action:'adjust',month:'2026-09',kind:'helpers',id:'2026-09:helpers:4',reason:'Teste',patch:{pallets:4}}));assert.equal(r.status,409);assert.equal(h.mutations(),0);});
