import test from 'node:test';import assert from 'node:assert/strict';
import {checkerProductivity,checkerVisual} from '../efc-checkers.mjs';
import {calculatePeriod} from '../efc-history.mjs';
const fixture=()=>({checkers:[{name:'A',date:'2026-10-01',map:'1',pallets:2,boxes:100},{name:'A',date:'2026-10-01',map:'2',pallets:3,boxes:200},{name:'B',date:'2026-10-02',map:'3',pallets:4,boxes:300}],errors:[{checker:'A',date:'2026-10-01',quantity:2},{checker:'A',date:'2026-10-01',quantity:1},{checker:'B',date:'2026-10-02',quantity:2}]});
test('conferente productivity uses own rows and own quality attribution',()=>{const c=fixture(),r=checkerProductivity(c),a=r.ranking.find(x=>x.name==='A');assert.equal(a.maps,2);assert.equal(a.pallets,5);assert.equal(a.boxes,300);assert.equal(a.occurrences,2);assert.equal(a.quantity,3);assert.equal(a.rate,.01);assert.equal(r.summary.maps,3);assert.equal(r.summary.pallets,9);assert.equal(r.summary.occurrences,3);assert.equal(r.daily[0].pallets,5);});
test('member filter changes every chart, total and quality row consistently',()=>{const r=checkerProductivity(fixture(),'B');assert.equal(r.ranking.length,1);assert.equal(r.summary.maps,1);assert.equal(r.summary.quantity,2);assert.equal(r.daily.length,1);assert.equal(r.daily[0].date,'2026-10-02');});
test('same map has a single box denominator and unknown quantities remain absent',()=>{const c=fixture();c.checkers.push({...c.checkers[0]});assert.equal(checkerProductivity(c,'A').ranking[0].boxes,300);c.checkers[1].boxes=null;const a=checkerProductivity(c,'A').ranking[0];assert.equal(a.boxes,null);assert.equal(a.rate,null);assert.equal(a.missing,1);});
test('period filter updates checker records and quality without modifying input',()=>{const d=fixture();const c=calculatePeriod(d,'2026-10','2026-10-02');assert.equal(checkerProductivity(c).summary.maps,1);assert.equal(checkerProductivity(c).summary.occurrences,1);assert.equal(d.checkers.length,3);});
test('quality-only checker remains visible and identifiers are escaped',()=>{const c=fixture();c.errors.push({checker:'<New>',date:'2026-10-02',quantity:4});assert.equal(checkerProductivity(c).ranking.length,3);const html=checkerVisual(c,{});assert.match(html,/&lt;NEW&gt;/);assert.match(html,/data-efc-chart-checker=/);assert.doesNotMatch(html,/data-efc-chart-member=/);assert.match(html,/Taxa de erros/);});
