const fs=require('fs');
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const HEADERS=['Nr. Mapa','Data Emisssão Mapa','Status Mapa','Tipo Mapa','Cód. Armazém','Desc. Armazém','Placa',...['Capacidade Veic. Pallet','Qt. Utilizada Mapa Pallet'].flatMap(x=>[14,21,28,35,42].map(n=>x+' '+n)),'Qt. Baias Vazias','Desc. Pallet','Cód. Produto','Desc. Produto','Cód. Embalagem','Desc. Embalagem','Cód. Área de Separação','Desc. Área de Separação','Qt. Lastros','Qt. Caixas Pallet','Qt. Unidade','Pallet Fechado','Seq. Item','Seq. Entrega','Rotina','Tipo OCP','Mapas Entrega'];
function records(text){const out=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++}else if(quoted||!field)quoted=!quoted;else field+=c;}else if(c===';'&&!quoted){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(x=>x.trim()))out.push(row);row=[];field=''}else field+=c;}if(quoted)throw Error('OCP_CSV_UNCLOSED_QUOTE');if(field||row.length){row.push(field);if(row.some(x=>x.trim()))out.push(row)}return out;}
function number(s){if(s==='')return null;const t=s.trim();if(!/^-?\d+(?:[,.]\d+)?$/.test(t))throw Error('OCP_INVALID_QUANTITY');return Number(t.replace(',','.'));}
function date(s){const m=/^(\d{2})\/(\d{2})\/(\d{4})$/.exec(s);if(!m)throw Error('OCP_INVALID_DATE');const d=m[3]+'-'+m[2]+'-'+m[1];if(new Date(d+'T12:00:00Z').toISOString().slice(0,10)!==d)throw Error('OCP_INVALID_DATE');return d;}
function parseText(text){const lines=records(text.replace(/^\uFEFF/,''));const headers=lines.shift();if(!headers||headers.length!==34||headers.some((x,i)=>norm(x)!==norm(HEADERS[i])))throw Error('OCP_HEADERS_MISMATCH');const rows=lines.map((values,i)=>{if(values.length===35&&values[34]==='')values.pop();if(values.length!==34)throw Error('OCP_COLUMN_COUNT: '+(i+2));if(!/^\d{1,12}$/.test(values[0])||!/^\d{1,12}$/.test(values[19]))throw Error('OCP_INVALID_MAP_OR_PRODUCT');for(const n of [...Array.from({length:11},(_,n)=>n+7),25,26,27,29,30])number(values[n]);if(!['SIM','NAO'].includes(norm(values[28])))throw Error('OCP_INVALID_CLOSED_PALLET');return{row_no:i+1,date:date(values[1]),map:String(Number(values[0])),plate:values[6].toUpperCase().replace(/[^A-Z0-9]/g,''),product:String(Number(values[19])),pallet:values[18],closed:norm(values[28])==='SIM',boxes:number(values[26]),units:number(values[27]),raw_values:values};});if(!rows.length)throw Error('OCP_EMPTY_REPORT');return{headers,rows,maps:[...new Set(rows.map(r=>r.map))],dates:[...new Set(rows.map(r=>r.date))].sort()};}
function parse03023601(file){const b=fs.readFileSync(file);let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(b)}catch{text=new TextDecoder('windows-1252').decode(b)}return parseText(text);}
module.exports={parse03023601,parseText,HEADERS};
