(() => {
  const API='https://wzawtpadchtnvtclyghm.supabase.co/functions/v1/receiving-nri-api';
  const $=id=>document.getElementById(id);
  let token=sessionStorage.getItem('gate_token')||'',editing=null;

  async function call(action,payload={},auth=true){const headers={'Content-Type':'application/json'};if(auth&&token)headers['x-gate-token']=token;const r=await fetch(API,{method:'POST',headers,body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({error:'Resposta inválida'}));if(!r.ok)throw new Error(d.error||'Erro na Portaria');return d}
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fd=v=>{const p=String(v||'').slice(0,10).split('-');return p.length===3?p[2]+'/'+p[1]+'/'+p[0]:'—'};
  const ft=v=>String(v||'').slice(0,5)||'—';
  function toast(msg,error=false){const t=$('toast');t.textContent=msg;t.classList.toggle('error',error);t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),3000)}
  function show(id){$('loginView').classList.toggle('hidden',id!=='loginView');$('homeView').classList.toggle('hidden',id!=='homeView')}
  function today(){return new Date().toLocaleDateString('sv-SE',{timeZone:'America/Sao_Paulo'})}function now(){return new Date().toLocaleTimeString('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit'})}
  function resetForm(){editing=null;$('receiptForm').reset();$('arrivalDate').value=today();$('arrivalTime').value=now();$('cancelEditButton').classList.add('hidden');$('saveButton').textContent='Abrir recebimento';$('formError').textContent=''}
  async function restore(){if(!token)return show('loginView');try{await call('gate_session');show('homeView');resetForm();loadReceipts()}catch{token='';sessionStorage.removeItem('gate_token');show('loginView')}}
  $('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').textContent='';const b=$('loginButton');b.disabled=true;try{const d=await call('gate_login',{pin:$('pinInput').value},false);token=d.token;sessionStorage.setItem('gate_token',token);$('pinInput').value='';show('homeView');resetForm();loadReceipts()}catch(err){$('loginError').textContent=err.message}finally{b.disabled=false}};
  $('logoutButton').onclick=async()=>{try{await call('gate_logout')}catch{}token='';sessionStorage.removeItem('gate_token');show('loginView')};
  $('refreshButton').onclick=loadReceipts;$('cancelEditButton').onclick=resetForm;

  function collect(){return{truck_number:$('truckNumber').value,factory_name:$('factoryName').value,driver_name:$('driverName').value,arrival_date:$('arrivalDate').value,arrival_time:$('arrivalTime').value,plate:$('plate').value,nf_imperio:$('nfImperio').value,nf_ambev:$('nfAmbev').value,map_number:$('mapNumber').value,order_number:$('orderNumber').value,fleet:$('fleet').value,shift:$('shift').value,gate_reception:$('gateReception').value,portaria_comments:$('comments').value}}
  $('receiptForm').onsubmit=async e=>{e.preventDefault();$('formError').textContent='';const b=$('saveButton');b.disabled=true;try{const d=editing?await call('gate_update_receipt',{id:editing.id,receipt:collect()}):await call('gate_create_receipt',{receipt:collect()});toast(editing?'Recebimento atualizado.':'Carreta aberta: '+d.receipt.display_name);resetForm();await loadReceipts()}catch(err){$('formError').textContent=err.message}finally{b.disabled=false}};
  function edit(r){editing=r;$('truckNumber').value=r.truck_number||'';$('factoryName').value=r.factory_name||'';$('driverName').value=r.driver_name||'';$('arrivalDate').value=String(r.arrival_date||'').slice(0,10);$('arrivalTime').value=String(r.arrival_time||'').slice(0,5);$('plate').value=r.plate||'';$('nfImperio').value=r.nf_imperio||'';$('nfAmbev').value=r.nf_ambev||'';$('mapNumber').value=r.map_number||'';$('orderNumber').value=r.order_number||'';$('fleet').value=r.fleet||'';$('shift').value=r.shift||'';$('gateReception').value=r.gate_reception||'';$('comments').value=r.portaria_comments||'';$('saveButton').textContent='Salvar alterações';$('cancelEditButton').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
  async function loadReceipts(){$('receiptList').innerHTML='<div class="receipt-card">Carregando...</div>';try{const d=await call('gate_list_receipts');const rows=d.receipts||[];$('receiptList').innerHTML=rows.length?rows.map(r=>'<article class="receipt-card"><div class="receipt-head"><div class="receipt-name">'+esc(r.display_name)+'</div><span class="status '+r.status+'">'+({awaiting_conference:'Aguardando conferência',in_conference:'Em conferência',conference_completed:'Concluída',cancelled:'Cancelada'}[r.status]||r.status)+'</span></div><div class="receipt-meta"><span>'+fd(r.arrival_date)+' '+ft(r.arrival_time)+'</span><span>Placa '+esc(r.plate||'—')+'</span><span>NF '+esc(r.nf_imperio||r.nf_ambev||'—')+'</span><span>Pedido '+esc(r.order_number||'—')+'</span></div>'+(r.status==='awaiting_conference'?'<div class="receipt-actions"><button class="secondary" data-edit="'+r.id+'">Editar</button></div>':'')+'</article>').join(''):'<div class="receipt-card">Nenhuma carreta aberta hoje.</div>';$('receiptList').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const r=rows.find(x=>String(x.id)===b.dataset.edit);if(r)edit(r)})}catch(e){$('receiptList').innerHTML='<div class="receipt-card error">'+esc(e.message)+'</div>'}}
  resetForm();restore();
})();