create table if not exists public.temperature_readings (
  id bigint generated by default as identity primary key,
  reading_date date not null,
  shift text not null check (shift in ('MANHÃ','TARDE','NOITE')),
  area text not null check (area in ('Câmara Fria','Retornável','Descartável','Repack','Marketplace')),
  temp_1 numeric(6,2) not null,
  temp_2 numeric(6,2),
  temperature numeric(6,2) not null,
  status text not null check (status in ('ok','attention','critical')),
  conferencer_id uuid references public.bo_conferencers(id) on delete set null,
  conferencer_name text,
  source text not null default 'site' check (source in ('historical_import','site')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (reading_date, shift, area)
);

create index if not exists temperature_readings_date_idx
  on public.temperature_readings(reading_date desc);
create index if not exists temperature_readings_area_date_idx
  on public.temperature_readings(area, reading_date desc);
create index if not exists temperature_readings_status_date_idx
  on public.temperature_readings(status, reading_date desc);

alter table public.temperature_readings enable row level security;

comment on table public.temperature_readings is
'Controle de temperatura do armazém. Armazena somente dados normalizados; arquivos históricos originais não são enviados ao Supabase.';
