import {mergeEvents} from './shared-031120.mjs';
import {createClient} from 'jsr:@supabase/supabase-js@2.57.4';
const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
const H={'Access-Control-Allow-Origin':'https://painel-armaz-m.gabrielysilva27.workers.dev','Access-Control-Allow-Headers':'content-type,x-session-token,x-agent-token','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Content-Type':'application/json','Cache-Control':'no-store'};
const reply=(x:unknown,status=200)=>new Response(JSON.stringify(x),{status,headers:H});
async function hash(t:string){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t)));return btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');}
function check(e:any){if(e)throw e;}
async function all(make:()=>any){const rows:any[]=[];for(let n=0;n<50000;n+=1000){const {data,error}=await make().range(n,n+999);check(error);rows.push(...data);if(data.length<1000)return rows;}throw Error('Limite de consulta excedido');}
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return reply({ok:true});if(req.method==='GET')return reply({service:'efc-api',version:'2026-10-02-mapas-1'});if(req.method!=='POST')return reply({error:'Método inválido'},405);
 try{
 const b=await req.json();
 if(b.action==='agent_maps'){
  const token=req.headers.get('x-agent-token');if(!token)return reply({error:'Agente não autorizado'},401);
  const {data:node,error}=await db.from('receiving_pull_agent_nodes').select('id').eq('token_hash',await hash(token)).eq('active',true).eq('slot_code','ADM').maybeSingle();check(error);if(!node)return reply({error:'Agente ADM necessário'},403);
  const date=String(b.reference_date||''),source=String(b.source_file||'');
  if(!/^2026-\d{2}-\d{2}$/.test(date)||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date||!/(^|[\\/])MAPAS[^\\/]*\.xlsx$/i.test(source)||source.length>500||!Array.isArray(b.rows)||!b.rows.length||b.rows.length>5000||JSON.stringify(b.rows).length>2000000)return reply({error:'Planilha MAPAS inválida'},400);
  const rows=b.rows.map((r:any,i:number)=>{const plate=String(r.plate||'').toUpperCase().replace(/[^A-Z0-9]/g,''),vehicle=String(r.vehicle||'');if(!/^\d{1,12}$/.test(vehicle)||!/^\w{5,12}$/.test(plate))throw Error('Veículo MAPAS inválido');return{...r,id:'maps-agent:'+date+'|'+i,date,plate,vehicle,eligible:r.eligible!==false,source:'MAPAS agente',agent_source:source};});
  const {error:ie}=await db.from('efc_agent_map_files').upsert({reference_date:date,source_file:source,rows,agent_node_id:node.id,updated_at:new Date().toISOString()},{onConflict:'reference_date'});check(ie);return reply({ok:true,imported:rows.length});
 }
 if(b.action==='agent_events'){
  const t=req.headers.get('x-agent-token');if(!t)return reply({error:'Agente não autorizado'},401);
  const {data:node,error}=await db.from('receiving_pull_agent_nodes').select('id').eq('token_hash',await hash(t)).eq('active',true).maybeSingle();check(error);if(!node)return reply({error:'Agente não autorizado'},403);
  if(!Array.isArray(b.rows)||b.rows.length>500||JSON.stringify(b.rows).length>400000)return reply({error:'Lote inválido'},400);
  const rows=b.rows.map((x:any)=>{if(!/^\d{1,12}$/.test(x.map)||!/^2026-\d{2}-\d{2}$/.test(x.date)||!/^([01]\d|2[0-3]):[0-5]\d:[0-5]\d$/.test(x.time)||!/^\w{5,12}$/.test(x.plate)||!['Carregado','Carga Montada'].includes(x.phase))throw Error('Evento inválido');const payload={map:x.map,date:x.date,time:x.time,phase:x.phase,plate:x.plate,vehicle:String(x.vehicle||'').slice(0,12),user:String(x.user||'').slice(0,100),system:String(x.system||'').slice(0,40),emission:x.emission||null,boxes:Number.isFinite(x.boxes)?x.boxes:null};return{id:[x.map,x.phase,x.date,x.time].join('|'),reference_date:x.date,payload,source_file:String(b.source_file||'031120').slice(0,180),updated_at:new Date().toISOString()};});
  if(rows.length){const {error}=await db.from('efc_agent_events').upsert(rows,{onConflict:'id'});check(error);}return reply({ok:true,imported:rows.length});
 }
 const token=req.headers.get('x-session-token');if(!token)return reply({error:'Sessão necessária'},401);
 const {data:s,error:se}=await db.from('app_sessions').select('user_id').eq('token_hash',await hash(token)).gt('expires_at',new Date().toISOString()).maybeSingle();check(se);if(!s)return reply({error:'Sessão expirada'},401);
 const {data:u,error:ue}=await db.from('app_users').select('id,role').eq('id',s.user_id).eq('active',true).maybeSingle();check(ue);if(!u)return reply({error:'Acesso negado'},403);
 const month=String(b.month||'');if(!/^2026-(0[1-9]|1[0-2])$/.test(month))return reply({error:'Mês inválido'},400);
 if(b.action==='adjust'){
  if(month<='2026-09')return reply({error:'Histórico fechado: os resultados originais do Excel foram preservados.'},409);
  if(u.role!=='admin')return reply({error:'Acesso administrativo necessário'},403);
  const kinds:any={helpers:['name','map','date','vehicle','pallets','start','end'],checkers:['name','map','date','vehicle','pallets'],priority:['priority'],capacity:['positions','palletization'],legacy_pay:['absences','compensation'],pcd:['eligible']};
  const allowed=kinds[b.kind],id=String(b.id||''),reason=String(b.reason||'').trim();if(!allowed||!id.startsWith(month+':'+b.kind+':')||!reason||reason.length>1000)return reply({error:'Correção inválida'},400);
  const {data:chunks,error}=await db.from('efc_archive').select('payload').eq('month',month).eq('kind',b.kind);check(error);if(!chunks?.some(c=>c.payload.some((r:any)=>r.id===id)))return reply({error:'Registro ausente'},404);
  const patch:any={};for(const [key,value] of Object.entries(b.patch||{})){if(!allowed.includes(key))return reply({error:'Campo não permitido'},400);if(['pallets','priority','positions','palletization','absences','compensation'].includes(key)){if(typeof value!=='number'||!Number.isFinite(value)||value<0||value>100000)return reply({error:'Número inválido'},400);}else if(key==='eligible'){if(typeof value!=='boolean')return reply({error:'Elegibilidade inválida'},400);}else if(key==='date'){if(typeof value!=='string'||!value.startsWith(month)||!/^2026-\d{2}-\d{2}$/.test(value))return reply({error:'Data inválida'},400);}else if(['start','end'].includes(key)){if(value!==null&&!/^([01]\d|2[0-3]):[0-5]\d(:[0-5]\d)?$/.test(String(value)))return reply({error:'Hora inválida'},400);}else if(typeof value!=='string'||value.length>160)return reply({error:'Texto inválido'},400);patch[key]=value;}
  if(!Object.keys(patch).length)return reply({error:'Informe uma alteração'},400);
  const {error:ae}=await db.rpc('efc_save_adjustment',{p_id:id,p_month:month,p_kind:b.kind,p_patch:patch,p_reason:reason,p_user:u.id});check(ae);return reply({ok:true});
 }
 if(b.action==='request_scan'){if(u.role!=='admin')return reply({error:'Acesso administrativo necessário'},403);const {data:node,error:ne}=await db.from('receiving_pull_agent_nodes').select('id').eq('slot_code','ADM').eq('active',true).maybeSingle();check(ne);if(!node)return reply({error:'Agente ADM indisponível para leitura das bases.'},503);const today=new Date().toLocaleDateString('sv-SE',{timeZone:'America/Sao_Paulo'}),dateFrom=new Date(Date.parse(today+'T12:00:00Z')-6*86400000).toISOString().slice(0,10);const {error:re}=await db.from('receiving_pull_031120_state').update({stage:'force_run',date_from:dateFrom,date_to:today,updated_at:new Date().toISOString()}).eq('agent_node_id',node.id);check(re);const {error}=await db.from('efd_agent_config').update({diagnostic_requested:true,status:'pending'}).eq('id',1);check(error);return reply({ok:true,bases:['MAPAS','031120']});}
 if(b.action!=='dashboard')return reply({error:'Ação inválida'},400);
 const from=month+'-01',next=new Date(Date.UTC(2026,Number(month.slice(5)),1)).toISOString().slice(0,10),before=new Date(Date.parse(from+'T12:00:00Z')-2*86400000).toISOString().slice(0,10);
 const [chunks,patches,events,pcd,agent,history,shared]=await Promise.all([all(()=>db.from('efc_archive').select('*').eq('month',month).order('kind').order('chunk')),all(()=>db.from('efc_adjustments').select('*').eq('month',month).order('record_id')),all(()=>db.from('efc_agent_events').select('id,payload').gte('reference_date',before).lt('reference_date',next).order('id')),all(()=>db.from('efc_agent_map_files').select('*').gte('reference_date',from).lt('reference_date',next).order('reference_date')),db.from('efd_agent_config').select('status,last_scan_at,last_error').eq('id',1).single(),db.from('efc_workbook_history').select('payload').eq('month',month).maybeSingle(),all(()=>db.from('report_031120_current').select('reference_date,headers,raw_values,source_file,completed_at').gte('reference_date',before).lt('reference_date',next).order('reference_date').order('row_no'))]);check(agent.error);check(history.error);
 const data:any={};for(const c of chunks){data[c.kind]??=[];data[c.kind].push(...c.payload);}for(const p of patches){const row=data[p.kind]?.find((x:any)=>x.id===p.record_id);if(row){Object.assign(row,p.patch);row.adjustment_reason=p.reason;}}
 data.events=mergeEvents(data.events||[],events,shared);
 const covered=new Set(pcd.map((r:any)=>r.reference_date)),planned=(data.pcd||[]).filter((p:any)=>!covered.has(p.date));for(const file of pcd)planned.push(...file.rows);for(const p of planned){const matching=data.events.filter((e:any)=>e.emission===p.date&&e.plate===String(p.plate).replace(/[^A-Z0-9]/gi,'').toUpperCase());const fleets=[...new Set(matching.map((e:any)=>e.fleet).filter(Boolean))];if(!p.fleet&&fleets.length===1)p.fleet=fleets[0];}data.pcd=planned;
 return reply({month,data,history:history.data?.payload||null,agent:agent.data,sources:[...new Set([...chunks.map(c=>c.source),...shared.map((r:any)=>r.source_file),...pcd.map((r:any)=>r.source_file)])],coverage:{report_031120:{dates:[...new Set(shared.map((r:any)=>r.reference_date))],last_import_at:shared.map((r:any)=>r.completed_at).sort().at(-1)||null},maps:{dates:[...new Set(pcd.map((r:any)=>r.reference_date))],last_import_at:pcd.map((r:any)=>r.updated_at).sort().at(-1)||null}},adjustments:patches.length});
 }catch(e){console.error('efc-api',e);return reply({error:'Não foi possível processar EFC. Confira os dados e tente novamente.'},400);}
});
